// ============================================================================
// Guías 🎓 de las FUNCIONALIDADES nuevas (sep-2026: pronóstico, Shapley, pacing, fatiga, MMM-lite,
// redes, web, SEO/GEO, Mis tableros, alertas, copiloto). Mismo formato que KPI_KNOW (lib/knowledge.ts,
// que las fusiona): fórmula, referencia, cómo leer, mejor práctica, oportunidad, marco y palancas.
// Las fórmulas, umbrales y límites son los que implementa el código (cada entrada cita su lib).
// `tipo: "funcion"` = no es una métrica del catálogo (lib/metricas) sino una lectura/herramienta.
// Client-safe, sin imports de runtime.
// ============================================================================
import type { KpiKnow } from "./knowledge";

export const FUNC_KNOW: Record<string, KpiKnow> = {
  // ── Seguimiento Objetivos (/overview) ── lib/stats/meta.ts + lib/objetivos-pronostico.ts
  prob_meta: {
    name: "Cierre proyectado y probabilidad de meta",
    comoLeer: "Para cada indicador se estima cómo termina el año siguiendo su propia historia, y se prueban <b>2.000 escenarios posibles</b> con los errores que tuvo esa estimación en el pasado. El número grande es el cierre más probable (mediana); el rango va del escenario pesimista al optimista (p10–p90); la probabilidad es el % de escenarios que llegan a la meta del año. En los objetivos y la Salud de Marca se suma según los pesos del Mapa.",
    mejorPractica: "Leé la probabilidad, no solo el %: <b>≥70% probable · 30–70% en riesgo · &lt;30% improbable</b>. Con menos de 6 meses de dato, menos de 4 errores para medir o un error típico &gt;50% se muestra <b>dato insuficiente</b> (y el porqué en el tooltip): no es un cero.",
    oportunidad: "Un indicador que pesa mucho en el Mapa y pasa a 'en riesgo' con meses por delante es donde más conviene actuar: todavía hay tiempo de cambiar el cierre. Los que ya están 'improbables' en noviembre piden ajustar la meta, no apretar más.",
    marco: "Pace-to-goal: pronóstico ≠ meta ≠ plan. El pronóstico dice adónde vas si seguís igual; la brecha contra la meta es lo que el plan de acción tiene que cerrar.",
    formula: "Volumen: cierre = Σ meses (real donde hay, simulado donde falta). Tasa: promedio de esos meses. P(meta) = simulaciones con cierre ≥ meta ÷ 2.000 (≤ en KPIs 'menor es mejor').",
    benchmark: "Método: estacionalidad del año anterior (×tendencia) si hay 13+ meses; si no, suavizado exponencial. La historia previa solo se usa si tiene ≥10 meses con dato.",
    funnel: "transversal",
    palancas: [
      { accion: "Priorizar los KPIs de más peso en riesgo", modulo: "ciclo-aprender" },
      { accion: "Llevar la brecha a un plan de acción", modulo: "plan-de-accion" },
      { accion: "Recalibrar metas imposibles", modulo: "metas-mensuales" },
    ],
  },
  shapley: {
    name: "Qué explica el resultado (Shapley)",
    comoLeer: "Reparte lo que falta para el 100% en lo que va del año (100% − cumplimiento) entre los indicadores, planes y objetivos que lo explican, y hace lo mismo con el cambio del último mes contra el anterior. Barras azules suman, grises restan; los puntos <b>suman exacto</b> el total (método de Shapley).",
    mejorPractica: "Empezá por el indicador que más puntos resta: es donde una mejora mueve más el objetivo. Pasarse de la meta en uno no compensa a otro (cada indicador cuenta hasta 100%). En Pauta, 'por qué se movió' separa si cambió el volumen o la tasa.",
    oportunidad: "Si el mes cambió por un indicador que no está en tu plan de acción, hay algo que no estás manejando (la época del año, un dato que falta o una acción de otro equipo).",
    marco: "Valor de Shapley (teoría de juegos): cada KPI se lleva su aporte marginal promedio en todas las combinaciones posibles, incluso cuando entra o sale del cálculo por falta de dato. Es atribución contable, no causalidad.",
    formula: "Brecha = Σ aportes φᵢ, con φᵢ = promedio del cambio en el cumplimiento al sumar el KPI i sobre todos los órdenes posibles",
    funnel: "transversal",
    palancas: [
      { accion: "Atacar el KPI que más resta", modulo: "ciclo-aprender" },
      { accion: "Revisar pesos del Mapa", modulo: "modelo-objetivos-kpis" },
    ],
    tipo: "funcion",
  },
  salud_datos: {
    name: "Salud de los datos",
    comoLeer: "La línea bajo el título dice cuándo se actualizó cada fuente que alimenta el tablero (Meta Ads, DV360, Google Analytics, OMD…). El punto usa la <b>misma regla que Monitoreo</b>: verde si llegó a tiempo (hasta 1,5 veces lo que tarda normalmente), ámbar si está algo atrasada (hasta 3 veces) y rojo si está muy atrasada.",
    mejorPractica: "Antes de leer una caída, mirá esta línea: un 'mes bajo' con la fuente atrasada es un problema de carga, no de negocio. Cada fuente tiene su cadencia (Meta/DV360/GA4 24 h, Instagram 12 h, competencia 7 días, OMD 30 días, GfK 90 días).",
    oportunidad: "Una fuente siempre en rojo es un proceso a arreglar (la actualización automática, un permiso vencido o una carga manual): el detalle está en Monitoreo. Pasale el caso a quien mantiene el tablero.",
    marco: "Confianza en el dato: una decisión es tan buena como la frescura del dato que la sostiene.",
    formula: "Edad = ahora − última actualización de la fuente. Estado: ok ≤ 1,5× cadencia · atrasado ≤ 3× · crítico > 3×",
    funnel: "transversal",
    palancas: [{ accion: "Revisar procesos y cargas en Monitoreo", modulo: "conectar-fuentes" }],
    tipo: "funcion",
  },
  sugerir_metas: {
    name: "Sugerir metas",
    comoLeer: "Propone la meta de cada mes que todavía no cerró a partir de cómo viene el indicador ('si seguís igual'), con un nivel de <b>ambición</b>: conservadora +0%, realista +10%, agresiva +20% (en indicadores donde menos es mejor, baja el valor). Muestra la probabilidad de llegar, calculada con 2.000 escenarios.",
    mejorPractica: "Buscá metas exigentes pero alcanzables: una probabilidad de <b>20–50%</b> es desafiante y posible; menos de 10% suele ser imposible. 'Aplicar' solo carga los valores en el panel: revisalos y tocá Guardar. Los meses ya medidos no se tocan.",
    oportunidad: "Si con la ambición realista la probabilidad sale muy baja, el problema no es la meta: el indicador necesita algo nuevo (más presupuesto, otro contenido, otro canal) para cambiar su tendencia.",
    marco: "Metas difíciles pero alcanzables motivan más que las fáciles o las imposibles (Locke & Latham). El pronóstico es el piso de realidad sobre el que se fija la ambición.",
    formula: "Meta sugerida(mes) = pronóstico(mes) × (1 + ambición). P(llegar) = simulaciones que alcanzan la suma (volumen) o el promedio (tasa) de las metas sugeridas.",
    benchmark: "Con menos de 6 meses de historia se propone la línea base sin probabilidad.",
    funnel: "transversal",
    palancas: [
      { accion: "Metas mensuales con estacionalidad", modulo: "metas-mensuales" },
      { accion: "Cargar metas en el Mapa", modulo: "conectar-fuentes" },
    ],
    tipo: "funcion",
  },
  validar_mapa: {
    name: "Validar el Mapa con mis datos",
    comoLeer: "Revisa cada vínculo indicador → objetivo contra las ventas reales (participación de mercado de Drean según GfK): cuando el indicador sube o baja, ¿las ventas acompañan ese mismo mes o hasta 3 meses después? Se comparan los <b>cambios</b> de un mes a otro, para no confundir dos cosas que simplemente crecen juntas con una relación real.",
    mejorPractica: "Leé el nivel de evidencia junto al peso: <b>fuerte</b> = muy poco probable que sea casualidad (p ajustado &lt; 0,05) y se mueven bastante juntos (|r| ≥ 0,5); <b>moderada</b> = probablemente no es casualidad, o p &lt; 0,2 con r ≥ 0,3; <b>se mueve al revés</b> = relación clara pero en sentido contrario. Hacen falta 12 pares o más (13+ meses de GfK).",
    oportunidad: "Un indicador con evidencia fuerte que pesa 15% o menos podría pesar más; uno que pesa 25% o más sin evidencia merece revisión (o es un efecto de marca que tarda más en verse).",
    marco: "El Mapa es una hipótesis. Esto es asociación, no causa: puede haber estacionalidad común o un tercer factor. Sirve para recalibrar pesos en el cierre del trimestre, no para borrar KPIs de marca.",
    formula: "Pearson r entre Δlog(KPI) en t y Δlog(share) en t+k, k = 0..3; se informa el mejor rezago con IC 95% (Fisher z) y p corregido por Bonferroni (×4)",
    funnel: "transversal",
    palancas: [
      { accion: "Recalibrar pesos del Mapa", modulo: "ciclo-acelerar" },
      { accion: "El modelo objetivos → KPIs → pesos", modulo: "mapa-estrategico" },
      { accion: "Medición e incrementalidad", modulo: "medicion-atribucion" },
    ],
    tipo: "funcion",
  },

  // ── Plan de Medios (/performance) ── lib/pauta-pacing.ts, pauta-fatiga.ts, marca-activacion.ts, moneda.ts, stats/mmm.ts
  pacing: {
    name: "Ritmo de inversión (pacing)",
    comoLeer: "¿Vamos a gastar lo planificado este mes? (ritmo de inversión o pacing). Compara lo gastado a la fecha con la meta de Inversión del mes y estima el cierre con un <b>rango</b>: los medios que se leen solos (Meta, DV360, Google Ads, Ecommerce) se proyectan al ritmo de los días que van; lo que la agencia (OMD) ya cargó (vía pública, TV…) se toma como está; los medios que OMD todavía no cargó entran con su promedio (valor central) y su máximo (techo) de los últimos 3 meses.",
    mejorPractica: "El estado usa tolerancia <b>±10%</b>: 'por encima' si hasta el piso supera el plan +10%; 'por debajo' si ni el techo llega al plan −10%. Con menos de 5 días es preliminar. Los días se cuentan a la hora de la última sync de Meta, no 'hoy'.",
    oportunidad: "Si a mitad de mes se gasta menos de lo planeado, todavía se corrige: pedile a la agencia ampliar públicos, pagar más por aparecer (pujas) o activar un medio. Si se gasta de más temprano, el presupuesto se va a terminar antes de fin de mes.",
    marco: "Controlar el ritmo es la mitad de la ejecución del plan de medios: un buen plan que no se ejecuta en tiempo no compra el alcance previsto.",
    formula: "Proyección = API × (días del mes ÷ días transcurridos) + OMD cargado + [0 · promedio 3m · máximo 3m] de los pendientes. Desvío = central ÷ plan − 1",
    benchmark: "Mismo modelo por medio que el Tablero (Meta siempre por API, Performance Max fuera, DV360 USD→ARS con el fx del mes).",
    funnel: "transversal",
    palancas: [
      { accion: "Controlar ritmo de gasto vs plan", modulo: "benchmarks-medios" },
      { accion: "Reasignar lo que no se ejecuta", modulo: "reasignacion-inversion" },
      { accion: "Medios sin API y carga OMD", modulo: "medios-offline" },
    ],
  },
  fatiga: {
    name: "Fatiga creativa",
    comoLeer: "Una pieza está <b>cansada</b> (fatiga creativa) cuando la gente le responde bastante menos (<b>25% o más</b> de caída en el % que ve el video —VTR— o en el % que hace clic —CTR—) contra los 1-2 meses anteriores <b>mientras cada persona la ve más veces</b> (frecuencia): la misma gente la ve más y responde menos. Se mira mes a mes por pieza.",
    mejorPractica: "Solo opina con meses de ≥10.000 impresiones. 'Frecuencia alta' = frecuencia mensual &gt;5. DV360 no da alcance por pieza: usa la frecuencia de su línea (canal × categoría). El mes en curso es parcial (la frecuencia todavía acumula), así que la regla es conservadora.",
    oportunidad: "Pedile a la agencia que cambie o renueve la pieza cansada (otro arranque, otro formato u otra edición) y que pase su plata a la versión que sigue funcionando. Si muchas piezas tienen 'un solo mes', se están cambiando antes de gastarse (bien).",
    marco: "El desgaste creativo es la razón más común de que un medio 'deje de rendir' con la misma inversión.",
    formula: "Caída = tasa último mes ÷ tasa previa (ponderada por impresiones) − 1; fatiga si caída ≤ −25% y frecuencia sube",
    benchmark: "Meta sugiere 1,5–3 exposiciones por semana para recordación.",
    funnel: "awareness",
    palancas: [
      { accion: "Renovar creatividades", modulo: "creatividades" },
      { accion: "Tope de frecuencia", modulo: "alcance-frecuencia" },
    ],
  },
  gasto_diario: {
    name: "Inversión diaria por medio",
    comoLeer: "Cuánta plata gastó <b>cada día</b> cada medio que se lee solo de la plataforma (Meta, Google Search, Demand Gen). Sirve para ver a tiempo una pauta mal configurada que se gasta el presupuesto del mes en pocos días (pasó en agosto 2026: campañas de Meta de 3 días se llevaron el 66% del gasto del mes). Un punto rojo en el gráfico = un día que gastó mucho más que un día normal de ese medio. DV360 (YouTube y Programmatic) solo informa por mes: se compara lo que va del mes contra un mes normal.",
    mejorPractica: "<b>Día pico</b>: más de 3 veces la mediana de los días con gasto de las 2 semanas anteriores (y más de $150.000). <b>Mes normal</b>: la mediana de los últimos 3 meses cerrados del medio (así un mes cortado o con un pico no mueve la referencia), llevando cada mes a la escala del plan de Inversión del mes (meta de Pauta Mkt): si el plan del mes es el doble, lo normal también. <b>Urgente</b>: en 5 días o menos se gastó la mitad de un mes normal (al arrancar el mes o en cualquier tramo de 5 días); o va 1,5 veces más rápido de lo esperable en los primeros 10 días; o un solo día gastó el 20% de un mes normal. <b>Revisar</b>: va 1,2 veces más rápido de lo esperable o hubo un día pico en los últimos 3 días. Meta, mientras no tenga dato diario, se mira por mes y por campaña (campañas activas 5 días o menos que se llevaron gran parte del mes).",
    oportunidad: "Si aparece 'Urgente', pedile ese mismo día a la agencia que revise el presupuesto diario y las fechas de fin de las campañas de ese medio (el error típico es cargar el presupuesto total como diario, o una fecha de fin a los 3 días). Cada día que pasa sin corregir es plata que no compra el alcance previsto del resto del mes.",
    marco: "Controlar el gasto día a día es el primer control de ejecución del plan de medios: el mensual avisa tarde, cuando el presupuesto ya se fue.",
    formula: "Día pico: gasto del día > 3 × mediana(gasto de los días con gasto de los 14 previos). Esperable a hoy = mes normal × día ÷ días del mes. Ritmo = gastado en el mes ÷ esperable a hoy. % de un mes normal = gastado ÷ mediana de los 3 meses cerrados. Ráfaga = gasto de los últimos 5 días ÷ mes normal ≥ 50%",
    benchmark: "Mismos medios y fuentes que el Tablero: Meta por la API (no OMD), Google Search y Demand Gen de Google Ads (Performance Max fuera), DV360 en dólares pasados a pesos con el tipo de cambio del mes. Todo en $.",
    funnel: "transversal",
    palancas: [
      { accion: "Controlar el gasto diario con la agencia", modulo: "benchmarks-medios" },
      { accion: "Reasignar lo que se gastó de más o de menos", modulo: "reasignacion-inversion" },
    ],
    tipo: "funcion",
  },
  marca_activacion: {
    name: "Marca vs activación",
    comoLeer: "Cuánto de la inversión construye ventas futuras haciendo que te conozcan (<b>marca</b>: avisos para que te conozcan, video, TV, vía pública, radio) y cuánto busca vender hoy (<b>activación</b>: avisos de venta, ecommerce). Lo que busca que te consideren (visitas a la web, videos saltables, Demand Gen, búsqueda en Google) sirve a los dos y se reparte mitad y mitad. Respeta los filtros.",
    mejorPractica: "Comparalo con la referencia <b>60:40</b> (marca:activación, promedio B2C de Binet & Field / IPA). Se considera 'en línea' dentro de ±10 puntos. Es una referencia, no una regla: varía por categoría y etapa de la marca.",
    oportunidad: "Muchos trimestres con casi todo en activación agotan las ventas futuras (la participación de mercado empieza a caer más adelante); mucha marca sin activación deja ventas sin cerrar en los picos comerciales.",
    marco: "The Long and the Short of It (Binet & Field): la marca crece en el largo plazo, la activación vende en el corto. Se necesitan los dos en proporción.",
    formula: "% marca = (marca + 50% mixto) ÷ total; % activación = (activación + 50% mixto) ÷ total",
    benchmark: "Referencia 60:40 ±10 pts.",
    funnel: "transversal",
    palancas: [
      { accion: "Balancear marca y activación", modulo: "presupuesto-marketing" },
      { accion: "Plan de medios por etapa del funnel", modulo: "plan-de-medios" },
    ],
    tipo: "funcion",
  },
  moneda_montos: {
    name: "Moneda: $ o USD",
    comoLeer: "<b>$</b> = los montos tal como los informó cada fuente; <b>USD</b> = cada monto dividido por el dólar oficial promedio de su mes (BCRA). Las metas en pesos se convierten igual, así real y meta quedan en la misma moneda.",
    mejorPractica: "Con inflación, comparar pesos de meses lejanos engaña: para ver si la inversión creció de verdad o comparar con costos y benchmarks en dólares, usá USD. Si falta el dólar de un mes se usa el último disponible y se avisa (nunca un cero silencioso). La elección queda en el link (?moneda=).",
    oportunidad: "Una inversión que 'sube' en pesos y baja en dólares es un recorte real: los avisos tienen menos peso aunque el número crezca.",
    marco: "Leer series largas de montos en una moneda estable (USD) para que la inflación no parezca crecimiento.",
    formula: "USD = monto ÷ dólar oficial promedio del mes",
    funnel: "transversal",
    palancas: [{ accion: "Gobernar el presupuesto", modulo: "presupuesto-marketing" }],
    tipo: "funcion",
  },
  mmm: {
    name: "Qué aporta cada medio · MMM-lite",
    comoLeer: "Un modelo simple que estima cuánto de un resultado de la web (personas, compras o ventas en pesos) explica cada medio (modelo de mezcla de medios o MMM). Tiene en cuenta que el efecto de un aviso dura unos meses (<b>adstock</b>) y que cada peso extra rinde menos que el anterior (<b>saturación</b>). Muestra cuánto aporta cada medio, cuánto devuelve cada peso (ROI) y cuánto devolvería el próximo peso (ROI marginal), con un rango de pesimista a optimista.",
    mejorPractica: "Se habilita con <b>12 meses o más</b> cerrados de pauta y resultado, y con inversión que haya variado entre meses. Confianza: alta con 10 o más datos por cada cosa que estima, media con 4 o más, baja con menos; baja un escalón si dos medios casi siempre se invirtieron juntos (r ≥ 0,8) o si al probarlo con meses pasados se equivoca más de 20%. 'Sin evidencia' = el rango del medio incluye el cero.",
    oportunidad: "El ROI marginal dice dónde conviene poner el próximo peso: pasá plata del medio que ya está saturado al que todavía tiene margen. 'Optimizar' reparte dentro del 50%–200% de lo actual.",
    marco: "Misma familia que Robyn/Meridian, en chico. Es asociación condicionada al modelo, no causalidad: sin experimentos (geo/lift) no prueba incrementalidad.",
    formula: "y = base + tendencia + Σ β·Hill(Adstock(inversión)); ajuste bayesiano (ridge, β ≥ 0) + bootstrap por bloques",
    benchmark: "Meridian considera 'bajo' ~4 datos por parámetro y 'direccional' ~15.",
    funnel: "transversal",
    palancas: [
      { accion: "MMM, atribución e incrementalidad", modulo: "medicion-atribucion" },
      { accion: "Reasignar por retorno marginal", modulo: "reasignacion-inversion" },
    ],
    tipo: "funcion",
  },
  roi_marginal: {
    name: "ROI marginal",
    comoLeer: "Cuánto resultado agrega el <b>próximo</b> peso invertido en un medio, según cómo viene respondiendo (ROI marginal). No es lo mismo que el ROI promedio: un medio puede rendir bien en promedio y aun así estar saturado.",
    mejorPractica: "Pasá plata de los medios donde el próximo peso rinde poco a los que rinde mucho, hasta que se emparejen. Mirá siempre el rango de pesimista a optimista (p10–p90).",
    oportunidad: "Un medio donde el próximo peso rinde mucho y que recibe poca plata es el candidato a crecer.",
    marco: "Principio de equimarginalidad: el presupuesto está bien repartido cuando el último peso rinde lo mismo en todos los medios.",
    formula: "Δ resultado ÷ Δ inversión en el nivel actual de inversión (derivada de la curva Hill)",
    funnel: "transversal",
    palancas: [{ accion: "Reasignar por retorno marginal", modulo: "reasignacion-inversion" }],
  },
  intensidad_pauta: {
    name: "Intensidad de pauta de la competencia",
    comoLeer: "Meta no publica cuánto invierten ni a cuánta gente llegan los avisos comerciales en Argentina, así que se estima con lo que se ve en la Biblioteca de Anuncios de Meta. Índice de 0 a 100 contra las marcas comparadas (<b>100 = la marca que más pauta</b>).",
    mejorPractica: "Se leen hasta <b>40 avisos activos por marca</b>. Si una marca llega a ese tope, sus avisos se estiman con las versiones por creativo que informa Meta (collation) o su índice es un mínimo (≥). Los avisos se asignan por Página de Facebook o por nombre de página con palabra completa.",
    oportunidad: "Los 'avisos que más sostienen' (más días publicados y más versiones) son la mejor pista de qué mensaje le funciona a cada competidor.",
    marco: "Share of voice aproximado: en ausencia de inversión declarada, la actividad publicitaria visible es el mejor proxy de presión competitiva.",
    formula: "Índice = 100 × (35% activos + 20% mensajes distintos + 20% lanzados en 30 días + 15% sostenidos 30+ días + 10% plataformas), cada uno ÷ máximo del set",
    funnel: "awareness",
    palancas: [
      { accion: "Leer la competencia", modulo: "investigacion-competencia" },
      { accion: "Creatividades que funcionan", modulo: "creatividades" },
    ],
    tipo: "funcion",
  },

  // ── Redes (/redes) ── lib/ig-stories.ts, redes-contenido.ts, redes-competencia.ts, redes-temas.ts, fb-paid.ts
  stories_ig: {
    name: "Stories de Instagram",
    comoLeer: "Las Historias (Stories) se leen cada 6 horas mientras están publicadas (24 h) y se guarda el <b>máximo</b> visto: el alcance es un mínimo. Las barras muestran el alcance típico por Historia del mes (mediana).",
    mejorPractica: "Mirá cuánta gente <b>se va</b> (salidas ÷ vistas) y cuánta <b>responde</b> (respuestas ÷ alcance): una secuencia de la que se va mucha gente, cansa. No entran en la interacción por publicación ni en la comparación de formatos (su interacción se mide distinto).",
    oportunidad: "Stories con respuestas altas son conversación directa: usalas para encuestas, preguntas de producto y derivar a la tienda.",
    marco: "Las Stories sostienen frecuencia con la comunidad actual; el feed y los Reels son los que suman alcance nuevo.",
    formula: "Tasa de salida = salidas ÷ vistas. Tasa de respuesta = respuestas ÷ alcance",
    funnel: "fidelizacion",
    palancas: [{ accion: "Estrategia de contenido orgánico", modulo: "contenido-organico" }],
    tipo: "funcion",
  },
  formatos_horarios: {
    name: "Formatos y horarios propios",
    comoLeer: "Cómo rinde cada red y formato, usando solo publicaciones sin pauta que ya tuvieron tiempo de juntar su alcance (Instagram 7+ días, Facebook 60+ días), sin Historias. <b>Índice 100</b> = lo normal de la cuenta en esa red (mediana).",
    mejorPractica: "El mapa de día × franja (hora AR) controla por formato: cada post se mide contra la mediana de su red y formato. Solo se muestra con ≥20 posts maduros; la 'mejor celda' exige ≥3 posts (* = menos de 3). Formatos con menos de 5 posts = muestra chica.",
    oportunidad: "Pasá el calendario al formato y al horario con índice mayor a 120 de forma sostenida; no reacciones a un casillero con 1-2 publicaciones.",
    marco: "Usar medianas y posts maduros evita que un viral o un post de ayer distorsionen la lectura.",
    formula: "Índice ER = mediana ER del formato ÷ mediana ER de la red × 100. ER = interacciones ÷ alcance del post",
    funnel: "consideracion",
    palancas: [
      { accion: "Estrategia de contenido orgánico", modulo: "contenido-organico" },
      { accion: "Creatividad nativa del formato", modulo: "creatividades" },
    ],
    tipo: "funcion",
  },
  er_comparable: {
    name: "ER comparable (competencia)",
    comoLeer: "Interacción por seguidor de cada marca (engagement o ER) medida con publicaciones de la <b>misma antigüedad</b>, para que la comparación sea justa: una publicación de ayer todavía no juntó sus interacciones y una de hace 3 semanas sí.",
    mejorPractica: "Método por marca: <b>°</b> = foto a los 7 días de publicado (si hay ≥3 posts fotografiados, seguidores de ese momento); sin marca = mediana de posts con 7+ días; <b>*</b> = preliminar (pocos posts maduros). Es mediana, no promedio: un sorteo viral inflaba el promedio ~100×.",
    oportunidad: "Si un competidor de tamaño parecido te saca ventaja en interacción de forma sostenida, la diferencia está en el contenido o el formato, no en la audiencia.",
    marco: "Comparar a igual edad y con medianas es la condición mínima para un benchmark de redes honesto.",
    formula: "ER = (likes + comentarios) ÷ seguidores; mediana de los posts con ≥7 días (o de la foto a 7 días)",
    funnel: "consideracion",
    palancas: [{ accion: "Leer redes y competencia", modulo: "lectura-redes" }],
    tipo: "funcion",
  },
  pauta_probable: {
    name: "Pauta probable de la competencia",
    comoLeer: "No hay dato cierto de la pauta de otras marcas: se marca una publicación como probablemente promocionada cuando tiene muchas más reproducciones que lo normal para esa marca y red, y proporcionalmente poca interacción.",
    mejorPractica: "Regla: views ≥ <b>3×</b> la mediana de su marca y red y ≤ <b>1/3</b> de su interacción por view; <b>alta</b> = ≥5× y ≤1/5, o marcado como patrocinado por el scraper. Mínimo 8 posts con views por marca y red. Es una probabilidad, nunca un hecho.",
    oportunidad: "Los posts que la competencia elige impulsar dicen qué producto o mensaje prioriza este mes.",
    marco: "Inferencia por patrón: el alcance pago rompe la relación habitual entre vistas e interacción.",
    formula: "Probable si views ÷ mediana(views) ≥ 3 y (interacción/view) ÷ mediana ≤ 1/3",
    funnel: "awareness",
    palancas: [{ accion: "Investigación de competencia", modulo: "investigacion-competencia" }],
    tipo: "funcion",
  },
  temas_marca: {
    name: "Temas por marca",
    comoLeer: "Cada publicación recibe un tema corto (1-3 palabras) con una clasificación automática diaria (que reusa los temas ya usados). Participación = % de las publicaciones de la marca con ese tema; interacción (ER) = el valor típico de interacción por seguidor (mediana).",
    mejorPractica: "Los 'temas que rinden en la competencia y Drean casi no usa' exigen ≥4 posts de ≥2 marcas, ER ≥1,2× la mediana rival y menos de 5% de los posts propios.",
    oportunidad: "Un tema que genera mucha interacción en varios competidores es una idea de contenido barata de probar.",
    marco: "Análisis de gaps de contenido: qué conversación ocupa la categoría y cuál no ocupás.",
    formula: "Gap si ER mediana del tema ≥ 1,2 × mediana rival y share propio < 5%",
    funnel: "consideracion",
    palancas: [{ accion: "Estrategia de contenido orgánico", modulo: "contenido-organico" }],
    tipo: "funcion",
  },
  fb_organico_pago: {
    name: "Facebook orgánico vs pago",
    comoLeer: "Meta dejó de dar el alcance sin pauta (orgánico) de Facebook (jun-2026) y el dato nuevo no separa lo pagado de lo orgánico. El tablero saca del orgánico las publicaciones con pauta: las que Meta marca con <b>50% o más de vistas pagas</b> <b>o</b> las que llegan a muchísima más gente que lo normal con casi nada de interacción (alcance mayor a 20.000 y reacciones/alcance menor a 1%).",
    mejorPractica: "La heurística nunca se apaga: la API solo suma posts pautados, no 'destapa' uno ya filtrado. El reach de la Página no puede superar la suma de los posts orgánicos; si lo supera, se usa la suma.",
    oportunidad: "Por eso la meta del plan Redes se mide con Instagram. Usá Facebook para leer tendencia y contenido, no para fijar metas de alcance.",
    marco: "Un orgánico contaminado por pauta hace creer que el contenido rinde más de lo que rinde.",
    formula: "Pago si vistas pagas ÷ (pagas + orgánicas) ≥ 0,5, o reach > 20k y reacciones ÷ reach < 1%",
    funnel: "consideracion",
    palancas: [{ accion: "Leer redes: engagement de valor", modulo: "lectura-redes" }],
    tipo: "funcion",
  },

  // ── Web (/web) ── lib/web-forecast.ts, web-consent.ts, web-calidad.ts
  cierre_mes_web: {
    name: "Cierre proyectado del mes (web)",
    comoLeer: "Estima las compras y las ventas online del mes en curso: toma el ritmo de los últimos 14 días, ajustado por día de la semana (según las 8 semanas anteriores), lo multiplica por los días que faltan y le suma lo ya vendido.",
    mejorPractica: "El rango (de pesimista a optimista, p10–p90) sale de cuánto se equivocó este mismo cálculo en semanas anteriores. Con menos de 5 días del mes o menos de 14 días de historia es <b>preliminar</b> (sin rango). Si la meta cae dentro del rango, vas bien.",
    oportunidad: "Compará 'lo que hace falta por día' con lo que se hace hoy: si la diferencia es grande hace falta una acción (una promoción, más avisos de venta), no esperar.",
    marco: "Pace-to-goal diario: anticipar el cierre deja margen para intervenir antes de que el mes termine.",
    formula: "Cierre = real a la fecha + Σ días restantes (ritmo × factor del día de semana)",
    funnel: "conversion",
    palancas: [
      { accion: "Corregir el embudo", modulo: "web-cro" },
      { accion: "Campañas estacionales", modulo: "campanas-estacionales" },
    ],
    tipo: "funcion",
  },
  consent: {
    name: "Medición y consentimiento",
    comoLeer: "Responde una pregunta simple: <b>¿de cada 100 clics que pagamos en Google Ads, cuántos llegan a medirse en Google Analytics (GA4)?</b> Analytics no informa cuánta gente rechaza las cookies, así que se comparan las visitas que atribuye a los anuncios de Google (google / cpc) con los clics que informa Google Ads el mismo mes cerrado.",
    mejorPractica: "Si la medición está bien, Google Analytics ve <b>~75–100%</b> de los clics. Menos de 75% = parte de los clics no se mide; menos de 50% = se mide menos de la mitad; si la relación <b>cae</b> a menos del 70% de lo habitual (con la pauta estable) = algo cambió en el sitio. Mínimo 300 clics en el mes.",
    oportunidad: "Si el número está bajo, son tres pedidos a la agencia o al desarrollador: (1) que cada clic de Google Ads lleve su <b>marca de seguimiento</b> (etiquetado automático, <i>gclid</i>); (2) que el <b>cartel de cookies</b> deje a Analytics estimar las visitas de quien no acepta (<i>Consent Mode avanzado</i>); (3) que prueben las páginas de llegada de los anuncios con la herramienta gratuita de Google (<i>Tag Assistant</i>). Todo lo que Analytics no ve hace parecer que las campañas venden menos de lo que venden (conversión y retorno subestimados).",
    marco: "Sin medición completa, cualquier optimización se hace sobre una muestra sesgada.",
    formula: "% registrado = sesiones GA4 google/cpc ÷ clicks Google Ads (mes cerrado)",
    benchmark: "Sano 75–100%.",
    funnel: "conversion",
    palancas: [{ accion: "Configurar GA4 y eventos clave", modulo: "ga4-configuracion" }],
    tipo: "funcion",
  },
  calidad_ga4: {
    name: "Calidad del dato (GA4)",
    comoLeer: "Chequeo de cómo se mide la web en los últimos 28 días: si se registran las ventas, si cada compra llega con su valor y su moneda y sin repetirse, si se miden los pasos de la compra, si se sabe por qué página entró cada visita y de dónde vino, y si Google Analytics recorta datos. Sello: <b>confiable</b> (sin problemas), <b>con advertencias</b> o <b>incompleto</b> (algún problema serio).",
    mejorPractica: "Si una visita figura sin página de entrada ('(not set)') o sin canal ('Unassigned'): desde 5% es aviso, desde 20% es problema serio. Si se registran más de 1,2 compras por cada venta real, la compra se está contando de más. Cada punto trae 'cómo arreglarlo' para pasarle al equipo web.",
    oportunidad: "Arreglar la medición hace confiables todos los números de este tablero: es lo primero que hay que hacer si el sello no está en verde.",
    marco: "Garbage in, garbage out: la calidad del dato va antes que el análisis.",
    formula: "Sello = incompleto si hay fallas · con advertencias si hay avisos · confiable si no",
    funnel: "conversion",
    palancas: [
      { accion: "GA4: eventos clave y ecommerce", modulo: "ga4-configuracion" },
      { accion: "UTM y nomenclatura", modulo: "utm-nomenclatura" },
    ],
    tipo: "funcion",
  },
  embudo_ecommerce: {
    name: "Embudo de ecommerce",
    comoLeer: "Cuánta gente llega a cada paso de la compra (vio producto → carrito → pago → compra) en los últimos 28 días (azul) contra los 28 anteriores (gris). El % es cuántos pasan desde el paso anterior (embudo).",
    mejorPractica: "La 'mayor caída' es el paso que más empeoró contra el período anterior (con 50 personas o más de base) y estima las compras perdidas. Un paso en 0 entre dos que tienen datos = falta medir ese paso, no es que la gente abandone.",
    oportunidad: "Arreglá el paso que más cayó antes de traer más visitas: tapar una pérdida rinde sobre toda la gente que ya pagaste por traer.",
    marco: "Teoría de restricciones: la etapa más débil gobierna el resultado del embudo.",
    formula: "Tasa paso = usuarios del paso ÷ usuarios del paso anterior. Compras perdidas ≈ usuarios previos × (tasa previa − actual) × conversión del resto",
    funnel: "conversion",
    palancas: [{ accion: "Web, CRO y embudo", modulo: "web-cro" }],
    tipo: "funcion",
  },
  trafico_ia: {
    name: "Tráfico desde asistentes de IA",
    comoLeer: "Visitas que llegan desde ChatGPT, Gemini, Perplexity, Copilot, Claude y otros asistentes de IA (según Google Analytics), cuánto pesan en la web y si compran o consultan más o menos que el promedio.",
    mejorPractica: "Leelo junto a 'Visibilidad en IA' del tablero SEO: la visibilidad es cuánto te nombran; esto es cuánto tráfico te mandan. Conversión = compras (o eventos clave si no hay ecommerce) ÷ sesiones.",
    oportunidad: "Si esa gente compra más que el promedio, vale la pena trabajar para que la IA te cite (fichas con especificaciones, comparativas, preguntas frecuentes).",
    marco: "Los asistentes de IA son un canal de descubrimiento nuevo: todavía chico, crece rápido.",
    formula: "Share = sesiones desde IA ÷ sesiones del sitio",
    funnel: "consideracion",
    palancas: [{ accion: "SEO y Share of Search", modulo: "seo-share-of-search" }],
    tipo: "funcion",
  },
  landings_caida: {
    name: "Páginas de entrada en caída",
    comoLeer: "Páginas por donde entra la gente (landings) que perdieron visitas contra los 28 días anteriores y cayeron bastante más que el resto de la web (no es la caída general).",
    mejorPractica: "Criterio: caída ≥30%, al menos 20 puntos peor que el sitio, y base previa ≥ máx(50 sesiones, 1% del sitio). Ordenadas por sesiones perdidas.",
    oportunidad: "Cruzalo con 'Contenido que decae' de Search Console y con la pauta: una página que cae porque bajó en Google o por un link roto se recupera rápido.",
    marco: "Detección por excepción: aislar lo que se mueve distinto del total.",
    formula: "Δ = sesiones actuales ÷ previas − 1; entra si Δ ≤ −30% y Δ − Δ sitio ≤ −20 pp",
    funnel: "conversion",
    palancas: [
      { accion: "Search Console: diagnóstico", modulo: "search-console" },
      { accion: "Web y CRO", modulo: "web-cro" },
    ],
    tipo: "funcion",
  },

  // ── SEO / GEO (/seo-search) ── lib/marca-indices.ts, llmo-stats.ts, sc-deep.ts, seo-audit-core.ts, ctr-curve.ts
  salud_digital: {
    name: "Salud digital de marca",
    comoLeer: "Índice contra la competencia con lo que se mide todos los meses sin encuesta: cuánto te buscan en Google (share of search), cuánta interacción te llevás en redes (share of engagement), cuánto te nombra la IA y en qué lugar aparecés en Google. <b>50 = el promedio de las marcas comparadas</b>; cada 10 puntos arriba o abajo = bastante mejor o peor que el resto.",
    mejorPractica: "Mirá qué componente te empuja o te frena (vs el set en σ). Requiere ≥3 marcas y ≥2 componentes; el mes de referencia es el de más componentes entre los 3 últimos.",
    oportunidad: "Si el índice sube antes que la medición de Kantar, anticipa una buena próxima medición; si baja, reforzá el componente más flojo.",
    marco: "Señal viva de salud de marca entre olas de Kantar: conductual, no declarativa.",
    formula: "Índice = 50 + 10 × promedio de z por componente; z = (valor − promedio del set) ÷ desvío",
    funnel: "awareness",
    palancas: [
      { accion: "Posicionamiento y salud de marca", modulo: "salud-de-marca" },
      { accion: "SEO y Share of Search", modulo: "seo-share-of-search" },
    ],
  },
  esos: {
    name: "ESoS (share of search excedente)",
    comoLeer: "Diferencia entre tu parte de las búsquedas en Google (share of search, promedio de 6 meses) y tu parte de las ventas del mercado según GfK (últimos 12 meses, en unidades), por categoría (ESoS). Positivo = te buscan más de lo que vendés: las ventas tienden a subir.",
    mejorPractica: "Señal: <b>≥ +0,5 pp</b> sostenido <b>3+ meses</b> → el share tiende a subir; ≤ −0,5 pp → a bajar. Con 18+ meses se estima el rezago propio (r y pares). Solo meses cerrados.",
    oportunidad: "Una categoría donde te buscan menos de lo que vendés, mes tras mes, pide reforzar los avisos para que te conozcan y el posicionamiento en Google antes de que se note en las ventas.",
    marco: "Les Binet (IPA): el share of search anticipa el share de mercado.",
    formula: "ESoS = SoS (prom. 6m) − share de mercado GfK",
    benchmark: "±0,5 pp durante 3+ meses.",
    funnel: "consideracion",
    palancas: [
      { accion: "Share of Search como indicador adelantado", modulo: "seo-share-of-search" },
      { accion: "Balance marca / activación", modulo: "presupuesto-marketing" },
    ],
  },
  llmo_ic: {
    name: "Visibilidad en IA (con margen de error)",
    comoLeer: "% de respuestas del asistente de IA (buscando en internet, desde Argentina) que nombran a la marca, con su <b>margen de error</b> (intervalo de confianza de Wilson al 95%). 12 preguntas por categoría con 4 intenciones distintas, una vez por semana; se juntan 28 días de respuestas.",
    mejorPractica: "Antes de leer una diferencia, mirá si los rangos se solapan. <b>Dato insuficiente</b> con menos de 30 respuestas o margen mayor a ±20 pp. La 'posición en la IA' es ruido: la métrica útil es la tasa.",
    oportunidad: "'Fuentes que te faltan' = sitios que la IA cita cuando nombra a la competencia y no a Drean: ahí conviene estar (reseñas, comparadores, medios).",
    marco: "Las respuestas de IA son muy volátiles: solo una tasa sobre muchas corridas con su margen es estadísticamente válida.",
    formula: "Tasa = respuestas que mencionan la marca ÷ respuestas; IC Wilson 95%",
    benchmark: "n ≥ 30 y margen ≤ ±20 pp.",
    funnel: "consideracion",
    palancas: [{ accion: "SEO y Share of Search", modulo: "seo-share-of-search" }],
    tipo: "funcion",
  },
  kw_evolucion: {
    name: "Evolución por keyword",
    comoLeer: "Fotos de los resultados de Google para drean.com.ar en dos fechas: qué búsquedas entraron o salieron de los 10 primeros resultados y cuántas están entre los 3 primeros y los 10 primeros. '—' = fuera de los 100 primeros.",
    mejorPractica: "Ganadoras/perdedoras = cambio de ≥3 posiciones o entrada/salida del top-10, ponderado por volumen. Leé primero las perdedoras de alto volumen.",
    oportunidad: "Una búsqueda muy buscada que salió de los 10 primeros es la recuperación que más rinde: actualizá la página y sumá links hacia ella desde otras páginas del sitio.",
    marco: "El SEO se gana keyword por keyword; el índice promedio esconde los movimientos que importan.",
    formula: "Δ posición = posición final − inicial (top-100)",
    funnel: "consideracion",
    palancas: [{ accion: "SEO y Share of Search", modulo: "seo-share-of-search" }],
    tipo: "funcion",
  },
  sc_fondo: {
    name: "Search Console a fondo",
    comoLeer: "Tres lecturas sobre los datos de Google de tu propia web: <b>páginas que compiten entre sí</b> por la misma búsqueda (canibalización), <b>páginas que vienen perdiendo visitas</b> (con su causa probable) y <b>celular contra computadora</b>.",
    mejorPractica: "Canibalización: búsquedas sin marca con ≥200 impresiones en 90 días, posición media 3–20 y la 2ª URL con ≥15%. Decae: −20% de clics vs 90 días previos y −30% interanual (−35% si no hay interanual). Mobile: alerta si rankea ≥2 posiciones peor, si su CTR rinde &lt;70% del de desktop vs lo esperado, o si sus clics caen ≥20% y 15 pp más que desktop.",
    oportunidad: "Si dos páginas propias compiten por la misma búsqueda, Google no sabe cuál mostrar y ninguna sube: conviene <b>quedarse con una</b> (unirlas, redirigir la otra o indicarle a Google cuál es la principal —canonical—) o diferenciar su contenido. Si una página mantiene su lugar pero recibe menos clics, suele ser un Resumen de IA de Google arriba: buscá que te cite.",
    marco: "Search Console es la fuente de verdad del SEO orgánico: impresiones y clics reales, no estimados.",
    formula: "Clicks ganables/mes ≈ impresiones × (CTR esperado una posición arriba de la mejor URL − CTR observado) ÷ meses",
    funnel: "consideracion",
    palancas: [{ accion: "Search Console: diagnóstico", modulo: "search-console" }],
    tipo: "funcion",
  },
  ctr_curva: {
    name: "Curva de CTR esperado",
    comoLeer: "<b>De cada 100 personas que ven un resultado en Google, cuántas le hacen clic según el lugar en que aparece</b> (% de clics esperado por posición o CTR). Sirve para saber si una página se lleva los clics que su lugar promete: el 1° se lleva muchos más que el 5°. Con suficientes búsquedas sin marca se calcula con tus propios datos de Search Console por tramo (1, 2, 3, 4-5, 6-10, 11-20); si no, se usa una referencia de la industria (AWR jul-2026).",
    mejorPractica: "Referencia sin Resumen IA: pos 1 20% · 2 10,4% · 3 3,9% · 4 1,7% · 5 1,1% · 6 0,7% · 7-20 0,5% · &gt;20 0,1%. Con Resumen IA el top-5 cae (pos 1 9,7%). Un tramo propio necesita ≥15 búsquedas con ≥100 impresiones.",
    oportunidad: "Si una página recibe muchos menos clics de lo esperado para su lugar, lo primero es mejorar el <b>título y la descripción que muestra Google</b> (title y meta description) para que den ganas de entrar; a veces la causa es un Resumen de IA de Google que responde sin que la persona haga clic.",
    marco: "Hay mucha dispersión entre estudios de CTR: por eso los clics estimados se leen como rango y la curva propia manda.",
    formula: "CTR propio por tramo = Σ clics ÷ Σ impresiones (búsquedas sin marca), suavizado monótono",
    funnel: "consideracion",
    palancas: [{ accion: "Search Console: diagnóstico", modulo: "search-console" }],
    tipo: "funcion",
  },
  auditoria_seo: {
    name: "Auditoría técnica SEO / GEO",
    comoLeer: "Revisión semanal (lunes) de drean.com.ar: si Google puede mostrar las páginas, si deja entrar a los robots de la IA, el mapa del sitio, títulos y descripciones, contenido que depende de programación que Google no lee bien, y velocidad. Los problemas se ordenan por gravedad (error, advertencia, aviso) y por cuántos clics de Google afectan.",
    mejorPractica: "Salud técnica = % de páginas auditadas sin errores, −10 por cada error de todo el sitio. <b>'El sitio rechazó al auditor'</b> = las páginas y el robots.txt respondieron 403/5xx aun simulando un navegador: casi siempre un firewall/CDN que bloquea robots, no páginas rotas; no cuenta como error. Google sí lee el sitio (lo confirman Search Console y PageSpeed).",
    oportunidad: "Si el sitio no deja entrar a los robots de los buscadores con IA (ChatGPT, Claude, Perplexity: OAI-SearchBot, Claude-SearchBot, PerplexityBot en el archivo robots.txt), la marca desaparece de sus respuestas: es lo primero a pedirle al desarrollador que revise.",
    marco: "SEO técnico = condición necesaria: el mejor contenido no rankea si no se indexa.",
    formula: "Salud = (páginas sin error ÷ páginas auditadas) × 100 − 10 × errores de sitio",
    funnel: "consideracion",
    palancas: [{ accion: "Search Console: indexación y velocidad", modulo: "search-console" }],
    tipo: "funcion",
  },
  cwv: {
    name: "Core Web Vitals",
    comoLeer: "<b>Qué tan rápido carga y qué tan estable se ve la web en el celular</b>, medido con visitantes reales (Core Web Vitals). <b>LCP</b> = cuánto tarda en aparecer lo principal; <b>INP</b> = cuánto tarda en responder cuando tocás algo; <b>CLS</b> = cuánto 'salta' la página mientras carga.",
    mejorPractica: "Bueno: LCP ≤ 2,5 s · INP ≤ 200 ms · CLS ≤ 0,1. Malo: LCP &gt; 4 s · INP &gt; 500 ms · CLS &gt; 0,25. 'Usuarios reales' = CrUX de la URL (p75 de Chrome, 28 días); 'sitio completo' = CrUX del origen; 'laboratorio' = PageSpeed (una carga simulada, orientativa). Google rankea con el dato real.",
    oportunidad: "Si las páginas a las que llegan los anuncios tardan en cargar (LCP malo), cada clic pagado rinde menos: mucha gente se va antes de ver el producto. Mejorar la velocidad sube las ventas y además abarata la pauta de Google (Quality Score).",
    marco: "Page experience: los CWV son señal de ranking y, sobre todo, de conversión.",
    formula: "p75 mobile de LCP, INP y CLS (CrUX; si no hay, PageSpeed Insights lab)",
    benchmark: "LCP ≤ 2,5 s · INP ≤ 200 ms · CLS ≤ 0,1.",
    funnel: "conversion",
    palancas: [
      { accion: "Corregir velocidad e indexación", modulo: "search-console" },
      { accion: "Web y CRO", modulo: "web-cro" },
    ],
    tipo: "funcion",
  },

  // ── Diagnóstico ── lib/recomendacion.ts
  que_hacer: {
    name: "Qué hacer ahora",
    comoLeer: "Acciones concretas que salen de las alertas automáticas y del Diagnóstico IA, todas con el mismo formato: qué hacer, por qué (con números), qué se espera ganar, qué tan seguros estamos, cuánto trabajo lleva y cómo medirla. Ordenadas por prioridad. Podés marcar cada una como 'La voy a hacer', 'Hecha' o 'Descartar' y seguirla en 'Mis acciones'.",
    mejorPractica: "Prioridad = impacto (1-5) × confianza (alta 1 · media 0,7 · baja 0,4) ÷ esfuerzo (1 horas · 2 días · 3 semanas). Crítica ≥3 · alta ≥1,8 · media ≥0,9. Tomá pocas por ciclo y medilas antes/después en la ventana indicada.",
    oportunidad: "Las de mucho impacto y poco trabajo son las victorias rápidas del mes; las críticas que llevan mucho trabajo van al plan del trimestre.",
    marco: "Del insight a la acción: una recomendación sin dueño, medición ni prioridad no se ejecuta.",
    formula: "Prioridad = impacto × confianza ÷ esfuerzo",
    funnel: "transversal",
    palancas: [
      { accion: "De los insights al plan de acción", modulo: "plan-de-accion" },
      { accion: "Usar el Diagnóstico IA", modulo: "insights-chat" },
    ],
    tipo: "funcion",
  },

  // ── Mis tableros, alertas y copiloto ──
  armame_tablero: {
    name: "Armame el tablero",
    comoLeer: "Pedís en lenguaje natural lo que querés ver y la IA arma los gráficos con tus planillas y los datos del dashboard que tenés permitidos (Plan de Medios, Web, Redes IG, Seguimiento). Nunca se manda la data entera: solo columnas y 8 filas de muestra.",
    mejorPractica: "Sé específico con qué medir, cómo abrirlo y qué período ('inversión por medio y por mes, con el costo por mil impresiones'). Las métricas calculadas usan la fórmula oficial del catálogo (costo por mil o CPM, % de clics o CTR, costo por clic o CPC, frecuencia, interacción o ER). Revisá 'lo que entendí' y corregí antes de guardar.",
    oportunidad: "Armá una vez el tablero del comité mensual y compartilo por link o envío programado.",
    marco: "Autoservicio de datos con definiciones únicas: todos leen la misma métrica calculada igual.",
    formula: "Pedido → términos mapeados al catálogo de métricas → gráficos validados (si la IA falla, plan de respaldo determinístico)",
    funnel: "transversal",
    palancas: [
      { accion: "De dónde sale cada dato", modulo: "tableros-planilla" },
      { accion: "La revisión mensual", modulo: "reporte-mensual" },
    ],
    tipo: "funcion",
  },
  anotaciones: {
    name: "Anotaciones",
    comoLeer: "Qué pasó y cuándo ('lanzamiento TV', 'corte de stock'). Se marcan con una línea punteada en los gráficos por fecha de Mis tableros y el Diagnóstico IA las usa como contexto para explicar movimientos.",
    mejorPractica: "Anotá lanzamientos, cambios de precio, quiebres de stock, cambios en el sitio o en el tracking: son la causa más común de un salto que el dato solo no explica. Hasta 280 caracteres.",
    oportunidad: "Con anotaciones el Diagnóstico deja de adivinar: puede separar un efecto de campaña de un evento externo.",
    marco: "Memoria del negocio: los datos dicen qué pasó; las anotaciones, por qué.",
    formula: "Anotación = fecha + texto (≤ 280 caracteres), de este tablero o de todos; se dibuja como línea en esa fecha",
    funnel: "transversal",
    palancas: [{ accion: "Usar el Diagnóstico IA", modulo: "insights-chat" }],
    tipo: "funcion",
  },
  compartir_tablero: {
    name: "Compartir y envío programado",
    comoLeer: "Link de <b>solo lectura</b> firmado: quien lo tenga ve el tablero y sus datos sin iniciar sesión ni editar. Vence a los 7, 30 o 90 días; 'Dejar de compartir' lo invalida. El envío programado manda el link por mail (semanal: lunes · mensual: día 1).",
    mejorPractica: "El envío solo va a casillas de los dominios del equipo. Compartí el link con quien necesita ver, no editar (directorio, agencia).",
    oportunidad: "Un envío mensual fijo instala el ritual de revisión sin depender de que alguien arme el reporte.",
    marco: "Un solo número compartido evita versiones distintas del mismo dato.",
    formula: "Token = contenido + firma HMAC; válido si la firma coincide, no venció y no se revocó",
    funnel: "transversal",
    palancas: [{ accion: "La revisión mensual", modulo: "reporte-mensual" }],
    tipo: "funcion",
  },
  umbrales: {
    name: "Umbrales de alerta",
    comoLeer: "Avisos propios sobre el <b>último mes cerrado</b> (un mes parcial nunca dispara): 'supera', 'queda por debajo de', 'cae más de X%' o 'sube más de X%' vs el mes anterior. Usan las mismas series que Mis tableros y llegan como prioridad alta.",
    mejorPractica: "Hasta 10 avisos; los cambios van de 1% a 100%. El costo por mil impresiones (CPM) y el costo por clic (CPC) se calculan solo con los medios que informan impresiones (así TV y vía pública no los distorsionan). Poné avisos en lo que te obliga a actuar, no en todo.",
    oportunidad: "Un aviso sobre el costo por mil impresiones o sobre una caída de visitas detecta en días lo que una revisión mensual ve tarde.",
    marco: "Gestión por excepción: la atención va a la desviación relevante.",
    formula: "Dispara si valor(mes cerrado) > / < umbral, o si (valor ÷ mes anterior − 1) supera ±X%",
    funnel: "transversal",
    palancas: [{ accion: "Monitoreo y fuentes", modulo: "conectar-fuentes" }],
    tipo: "funcion",
  },
  copiloto_calidad: {
    name: "Calidad del copiloto",
    comoLeer: "Lo que el equipo calificó con 👍/👎 en 'Preguntale a tus datos' (últimos 90 días): % útiles, motivo más frecuente, fuentes con más respuestas malas (mín. 3 calificaciones) y las peores respuestas primero.",
    mejorPractica: "Revisá las 👎 y <b>verificá</b> las buenas (o corregidas): el copiloto las reusa como ejemplo de método en preguntas parecidas (similitud ≥0,4) y <b>siempre vuelve a consultar los números</b>, no copia la respuesta vieja.",
    oportunidad: "Una fuente con mucho 👎 marca una tool a mejorar o una pregunta frecuente para dejar verificada.",
    marco: "Un asistente mejora con feedback explícito y ejemplos curados por el equipo.",
    formula: "% útiles = 👍 ÷ calificaciones",
    funnel: "transversal",
    palancas: [{ accion: "Usar el copiloto para decidir", modulo: "insights-chat" }],
    tipo: "funcion",
  },
};

/** Alias (canon: minúsculas, sin tildes) → clave, para que kpiKnowFor resuelva los títulos de las secciones. */
export const FUNC_ALIASES: Record<string, string[]> = {
  prob_meta: ["cierre proyectado", "probabilidad de meta", "probabilidad de llegar a la meta", "pace to goal"],
  shapley: ["que explica el resultado", "que explica la brecha", "contribucion shapley", "shapley"],
  salud_datos: ["salud de los datos", "confianza en el dato", "frescura de datos"],
  sugerir_metas: ["sugerir metas", "metas sugeridas"],
  validar_mapa: ["validar con mis datos", "validacion de pesos", "tus pesos se sostienen en tus datos"],
  pacing: ["ritmo de inversion", "pacing"],
  fatiga: ["fatiga creativa", "fatiga creativa por pieza"],
  gasto_diario: ["inversion diaria por medio", "inversion diaria", "gasto diario", "gasto diario anomalo"],
  marca_activacion: ["marca vs activacion", "marca activacion", "60 40"],
  moneda_montos: ["moneda de los montos", "pesos o dolares", "montos en dolares"],
  mmm: ["mmm", "mmm lite", "que aporta cada medio", "que aporta cada medio mmm lite", "marketing mix model"],
  roi_marginal: ["roi marginal"],
  intensidad_pauta: ["indice de intensidad de pauta", "intensidad de pauta"],
  stories_ig: ["stories de instagram", "stories"],
  formatos_horarios: ["formatos y horarios propios", "formatos y horarios", "mejor dia y franja"],
  er_comparable: ["er comparable", "er comp", "engagement mediana"],
  pauta_probable: ["pauta probable de la competencia", "pauta probable"],
  temas_marca: ["temas por marca", "temas de contenido"],
  fb_organico_pago: ["facebook organico vs pago", "organico vs pago"],
  cierre_mes_web: ["cierre proyectado del mes", "cierre del mes"],
  consent: ["medicion y consentimiento", "consent mode", "consentimiento"],
  calidad_ga4: ["calidad del dato", "calidad del dato ga4"],
  embudo_ecommerce: ["embudo de ecommerce", "embudo ecommerce"],
  trafico_ia: ["trafico desde asistentes de ia", "trafico desde ia", "trafico ia"],
  landings_caida: ["paginas de entrada en caida", "landings en caida"],
  salud_digital: ["salud digital de marca", "salud digital de marca y esos", "indice digital"],
  esos: ["share of search vs share de mercado"],
  llmo_ic: ["visibilidad en ia con margen de error", "tasa de mencion"],
  kw_evolucion: ["evolucion por keyword"],
  sc_fondo: ["search console a fondo", "canibalizacion", "contenido que decae", "mobile vs desktop"],
  ctr_curva: ["curva de ctr", "ctr esperado"],
  auditoria_seo: ["auditoria tecnica", "auditoria tecnica seo geo", "salud tecnica"],
  cwv: ["core web vitals", "cwv"],
  que_hacer: ["que hacer ahora", "recomendaciones"],
  armame_tablero: ["armame el tablero"],
  anotaciones: ["anotaciones"],
  compartir_tablero: ["compartir", "link de solo lectura", "envio programado", "envio programado por mail"],
  umbrales: ["tus umbrales", "umbrales"],
  copiloto_calidad: ["calidad del copiloto"],
};
