// ============================================================================
// Guías 🎓 de las FUNCIONALIDADES nuevas (sep-2026: pronóstico, Shapley, pacing, fatiga, MMM-lite,
// redes, web, SEO/GEO, Mis tableros, alertas, copiloto). Mismo formato que KPI_KNOW (lib/knowledge.ts,
// que las fusiona): fórmula, referencia, cómo leer, mejor práctica, oportunidad, marco y palancas.
// Las fórmulas, umbrales y límites son los que implementa el código (cada entrada cita su lib).
// `tipo: "funcion"` = no es una métrica del catálogo (lib/metricas) sino una lectura/herramienta.
// Client-safe, sin imports de runtime.
// ============================================================================
import type { KpiKnow } from "./knowledge";

export const FUNC_KNOW: Record<string, KpiKnow> = {
  // ── Seguimiento Objetivos (/overview) ── lib/stats/meta.ts + lib/objetivos-pronostico.ts
  prob_meta: {
    name: "Cierre proyectado y probabilidad de meta",
    comoLeer: "Para cada KPI se pronostica el resto del año con su propia historia y se simulan <b>2.000 trayectorias</b> con los errores históricos del método. El número es la <b>mediana</b> del cierre; el rango, p10–p90; la probabilidad, el % de simulaciones que llegan a la meta anual. En objetivos y Salud de Marca se propaga por el rollup del Mapa.",
    mejorPractica: "Leé la probabilidad, no solo el %: <b>≥70% probable · 30–70% en riesgo · &lt;30% improbable</b>. Con menos de 6 meses de dato, menos de 4 errores para medir o un error típico &gt;50% se muestra <b>dato insuficiente</b> (y el porqué en el tooltip): no es un cero.",
    oportunidad: "Un KPI de mucho peso en el Mapa que pasa a 'en riesgo' con meses por delante es la intervención más rentable: todavía hay tiempo para mover el cierre. Los que ya están 'improbables' en noviembre piden recalibrar, no más presión.",
    marco: "Pace-to-goal: pronóstico ≠ meta ≠ plan. El pronóstico dice adónde vas si seguís igual; la brecha contra la meta es lo que el plan de acción tiene que cerrar.",
    formula: "Volumen: cierre = Σ meses (real donde hay, simulado donde falta). Tasa: promedio de esos meses. P(meta) = simulaciones con cierre ≥ meta ÷ 2.000 (≤ en KPIs 'menor es mejor').",
    benchmark: "Método: estacionalidad del año anterior (×tendencia) si hay 13+ meses; si no, suavizado exponencial. La historia previa solo se usa si tiene ≥10 meses con dato.",
    funnel: "transversal",
    palancas: [
      { accion: "Priorizar los KPIs de más peso en riesgo", modulo: "ciclo-aprender" },
      { accion: "Llevar la brecha a un plan de acción", modulo: "plan-de-accion" },
      { accion: "Recalibrar metas imposibles", modulo: "metas-mensuales" },
    ],
  },
  shapley: {
    name: "Qué explica el resultado (Shapley)",
    comoLeer: "Reparte la brecha del cumplimiento YTD (100% − cumplimiento) entre los KPIs, planes y objetivos que la causan, y el cambio del último mes contra el anterior. Barras azules suman, grises restan; los puntos <b>suman exacto</b> el total.",
    mejorPractica: "Empezá por el KPI que más puntos resta: es donde una mejora mueve más el objetivo. Un KPI sobrecumplido no compensa a otro (el rollup topea cada KPI en 100%). En Pauta, la línea 'por qué se movió' separa volumen y tasa (Shapley de 2 factores).",
    oportunidad: "Si el mes cambió por un KPI que no está en tu plan de acción, hay un efecto que no estás gestionando (estacionalidad, dato faltante o una acción de otro equipo).",
    marco: "Valor de Shapley (teoría de juegos): cada KPI se lleva su aporte marginal promedio en todas las combinaciones posibles, incluso cuando entra o sale del cálculo por falta de dato. Es atribución contable, no causalidad.",
    formula: "Brecha = Σ aportes φᵢ, con φᵢ = promedio del cambio en el cumplimiento al sumar el KPI i sobre todos los órdenes posibles",
    funnel: "transversal",
    palancas: [
      { accion: "Atacar el KPI que más resta", modulo: "ciclo-aprender" },
      { accion: "Revisar pesos del Mapa", modulo: "modelo-objetivos-kpis" },
    ],
    tipo: "funcion",
  },
  salud_datos: {
    name: "Salud de los datos",
    comoLeer: "La línea bajo el título dice cuándo se actualizó cada fuente que alimenta el tablero (Meta Ads, DV360, GA4, OMD…). El punto usa la <b>misma regla que Monitoreo</b>: verde si la última carga está dentro de 1,5× su cadencia esperada, ámbar hasta 3×, rojo más de 3×.",
    mejorPractica: "Antes de leer una caída, mirá esta línea: un 'mes bajo' con la fuente atrasada es un problema de carga, no de negocio. Cada fuente tiene su cadencia (Meta/DV360/GA4 24 h, Instagram 12 h, competencia 7 días, OMD 30 días, GfK 90 días).",
    oportunidad: "Una fuente en rojo sistemáticamente es un proceso a arreglar (workflow, token, carga manual): el detalle y el historial están en Monitoreo.",
    marco: "Confianza en el dato: una decisión es tan buena como la frescura del dato que la sostiene.",
    formula: "Edad = ahora − última actualización de la fuente. Estado: ok ≤ 1,5× cadencia · atrasado ≤ 3× · crítico > 3×",
    funnel: "transversal",
    palancas: [{ accion: "Revisar procesos y cargas en Monitoreo", modulo: "conectar-fuentes" }],
    tipo: "funcion",
  },
  sugerir_metas: {
    name: "Sugerir metas",
    comoLeer: "Propone la meta de cada mes que todavía no cerró a partir del pronóstico del KPI ('si seguís igual') por un nivel de <b>ambición</b>: conservadora +0%, realista +10%, agresiva +20% (en KPIs 'menor es mejor' baja el valor). Muestra la probabilidad de llegar con 2.000 simulaciones.",
    mejorPractica: "Buscá metas exigentes pero alcanzables: una probabilidad de <b>20–50%</b> es desafiante y posible; menos de 10% suele ser imposible. 'Aplicar' solo carga los valores en el panel: revisalos y tocá Guardar. Los meses ya medidos no se tocan.",
    oportunidad: "Si con la ambición realista la probabilidad sale muy baja, el problema no es la meta: el KPI necesita una acción nueva (presupuesto, contenido, canal) para cambiar su tendencia.",
    marco: "Metas difíciles pero alcanzables motivan más que las fáciles o las imposibles (Locke & Latham). El pronóstico es el piso de realidad sobre el que se fija la ambición.",
    formula: "Meta sugerida(mes) = pronóstico(mes) × (1 + ambición). P(llegar) = simulaciones que alcanzan la suma (volumen) o el promedio (tasa) de las metas sugeridas.",
    benchmark: "Con menos de 6 meses de historia se propone la línea base sin probabilidad.",
    funnel: "transversal",
    palancas: [
      { accion: "Metas mensuales con estacionalidad", modulo: "metas-mensuales" },
      { accion: "Cargar metas en el Mapa", modulo: "conectar-fuentes" },
    ],
    tipo: "funcion",
  },
  validar_mapa: {
    name: "Validar el Mapa con mis datos",
    comoLeer: "Contrasta cada vínculo KPI → objetivo con el resultado de negocio (share de mercado GfK de Drean): ¿las variaciones del KPI acompañan a las del share en el mismo mes o con hasta 3 meses de adelanto? Se trabaja en <b>variaciones</b> mes a mes para no confundir dos tendencias con una relación.",
    mejorPractica: "Leé el nivel de evidencia junto al peso: <b>fuerte</b> = p ajustado &lt; 0,05 y |r| ≥ 0,5; <b>moderada</b> = significativo, o p &lt; 0,2 con r ≥ 0,3; <b>se mueve al revés</b> = significativo con el signo contrario. Hacen falta ≥12 pares (13+ meses de GfK).",
    oportunidad: "Un KPI con evidencia fuerte que pesa ≤15% podría pesar más; uno que pesa ≥25% sin evidencia merece revisión (o es un efecto de marca de más largo plazo).",
    marco: "El Mapa es una hipótesis. Esto es asociación, no causa: puede haber estacionalidad común o un tercer factor. Sirve para recalibrar pesos en el cierre del trimestre, no para borrar KPIs de marca.",
    formula: "Pearson r entre Δlog(KPI) en t y Δlog(share) en t+k, k = 0..3; se informa el mejor rezago con IC 95% (Fisher z) y p corregido por Bonferroni (×4)",
    funnel: "transversal",
    palancas: [
      { accion: "Recalibrar pesos del Mapa", modulo: "ciclo-acelerar" },
      { accion: "El modelo objetivos → KPIs → pesos", modulo: "mapa-estrategico" },
      { accion: "Medición e incrementalidad", modulo: "medicion-atribucion" },
    ],
    tipo: "funcion",
  },

  // ── Plan de Medios (/performance) ── lib/pauta-pacing.ts, pauta-fatiga.ts, marca-activacion.ts, moneda.ts, stats/mmm.ts
  pacing: {
    name: "Ritmo de inversión (pacing)",
    comoLeer: "¿Vamos a invertir lo planificado este mes? Compara lo invertido a la fecha con la meta de Inversión del mes y proyecta el cierre con un <b>rango</b>: los medios con API (Meta, DV360, Google Ads, Ecommerce) se proyectan lineal por los días del dato; lo que OMD ya cargó (OOH, TV…) se toma como está; los medios sin API que OMD todavía no cargó entran con su promedio (central) y su máximo (techo) de los últimos 3 meses.",
    mejorPractica: "El estado usa tolerancia <b>±10%</b>: 'por encima' si hasta el piso supera el plan +10%; 'por debajo' si ni el techo llega al plan −10%. Con menos de 5 días es preliminar. Los días se cuentan a la hora de la última sync de Meta, no 'hoy'.",
    oportunidad: "Sub-ejecución a mitad de mes todavía se corrige (ampliar audiencias, subir pujas, activar un medio); sobre-ejecución temprana avisa que el presupuesto se agota antes del cierre.",
    marco: "Controlar el ritmo es la mitad de la ejecución del plan de medios: un buen plan que no se ejecuta en tiempo no compra el alcance previsto.",
    formula: "Proyección = API × (días del mes ÷ días transcurridos) + OMD cargado + [0 · promedio 3m · máximo 3m] de los pendientes. Desvío = central ÷ plan − 1",
    benchmark: "Mismo modelo por medio que el Tablero (Meta siempre por API, Performance Max fuera, DV360 USD→ARS con el fx del mes).",
    funnel: "transversal",
    palancas: [
      { accion: "Controlar ritmo de gasto vs plan", modulo: "benchmarks-medios" },
      { accion: "Reasignar lo que no se ejecuta", modulo: "reasignacion-inversion" },
      { accion: "Medios sin API y carga OMD", modulo: "medios-offline" },
    ],
  },
  fatiga: {
    name: "Fatiga creativa",
    comoLeer: "Una pieza está <b>fatigada</b> cuando su tasa de respuesta (VTR ≥50% en video, CTR en el resto) cae <b>≥25%</b> contra los 1-2 meses previos <b>mientras su frecuencia sube</b>: la misma gente la ve más veces y responde menos. Serie mensual por pieza (Meta por permalink, DV360 por creativo).",
    mejorPractica: "Solo opina con meses de ≥10.000 impresiones. 'Frecuencia alta' = frecuencia mensual &gt;5. DV360 no da alcance por pieza: usa la frecuencia de su línea (canal × categoría). El mes en curso es parcial (la frecuencia todavía acumula), así que la regla es conservadora.",
    oportunidad: "Rotá o refrescá la pieza fatigada (nuevo hook, formato o edición) y mové su presupuesto a la versión que sostiene la tasa. Muchas piezas 'con un solo mes' = rotan antes de desgastarse.",
    marco: "El desgaste creativo es la razón más común de que un medio 'deje de rendir' con la misma inversión.",
    formula: "Caída = tasa último mes ÷ tasa previa (ponderada por impresiones) − 1; fatiga si caída ≤ −25% y frecuencia sube",
    benchmark: "Meta sugiere 1,5–3 exposiciones por semana para recordación.",
    funnel: "awareness",
    palancas: [
      { accion: "Renovar creatividades", modulo: "creatividades" },
      { accion: "Tope de frecuencia", modulo: "alcance-frecuencia" },
    ],
  },
  marca_activacion: {
    name: "Marca vs activación",
    comoLeer: "Cuánto de la inversión construye demanda futura (<b>marca</b>: Awareness, video, TV/OOH/DOOH/radio) y cuánto captura la de hoy (<b>activación</b>: conversión, ecommerce). Consideración (tráfico, TrueView, Demand Gen, Search) sirve a los dos y se reparte 50/50. Respeta los filtros.",
    mejorPractica: "Comparalo con la referencia <b>60:40</b> (marca:activación, promedio B2C de Binet & Field / IPA). Se considera 'en línea' dentro de ±10 puntos. Es una referencia, no una regla: varía por categoría y etapa de la marca.",
    oportunidad: "Mucha activación por varios trimestres agota la demanda futura (el share empieza a caer con rezago); mucha marca sin activación deja ventas en la mesa en los picos comerciales.",
    marco: "The Long and the Short of It (Binet & Field): la marca crece en el largo plazo, la activación vende en el corto. Se necesitan los dos en proporción.",
    formula: "% marca = (marca + 50% mixto) ÷ total; % activación = (activación + 50% mixto) ÷ total",
    benchmark: "Referencia 60:40 ±10 pts.",
    funnel: "transversal",
    palancas: [
      { accion: "Balancear marca y activación", modulo: "presupuesto-marketing" },
      { accion: "Plan de medios por etapa del funnel", modulo: "plan-de-medios" },
    ],
    tipo: "funcion",
  },
  moneda_constante: {
    name: "Moneda: $ corrientes, constantes o USD",
    comoLeer: "Con inflación, comparar pesos de meses distintos engaña. <b>$ corrientes</b> = tal como lo informó la fuente; <b>$ constantes</b> = ajustado por IPC (INDEC) a pesos del último mes publicado; <b>USD</b> = dividido por el dólar oficial promedio del mes (BCRA). Las metas en pesos se convierten igual, así real y meta quedan en la misma moneda.",
    mejorPractica: "Para ver si la inversión creció de verdad, usá $ constantes; para comparar con costos o benchmarks en dólares, USD. Si falta el índice de un mes se usa el último disponible y se avisa (nunca un cero silencioso). La elección queda en el link (?moneda=).",
    oportunidad: "Una inversión que 'sube' en corrientes y baja en constantes es un recorte real: la presión de medios cae aunque el número crezca.",
    marco: "Moneda constante: la única forma honesta de leer series de montos largas en Argentina.",
    formula: "Constantes = monto × IPC(base) ÷ IPC(mes del monto). USD = monto ÷ dólar oficial promedio del mes",
    funnel: "transversal",
    palancas: [{ accion: "Gobernar el presupuesto", modulo: "presupuesto-marketing" }],
  },
  mmm: {
    name: "Qué aporta cada medio · MMM-lite",
    comoLeer: "Modelo de mix de medios chico: estima cuánto de un resultado de GA4 (usuarios, transacciones o ingresos) explica cada medio, con <b>adstock</b> (el efecto sigue unos meses) y <b>saturación</b> (cada peso adicional rinde menos). Muestra contribución, ROI y ROI marginal con banda p10–p90.",
    mejorPractica: "Se habilita con <b>12+ meses</b> cerrados de pauta y resultado, e inversión que varíe entre meses. Confianza: alta con ≥10 datos por parámetro, media ≥4, baja debajo; baja un escalón si dos medios se invierten casi siempre juntos (r ≥ 0,8) o si el backtest erra más de 20%. 'Sin evidencia' = la banda del medio incluye cero.",
    oportunidad: "El ROI marginal dice dónde va el próximo peso: mover presupuesto del medio saturado al que todavía tiene pendiente. 'Optimizar' reparte dentro de 50%–200% de lo actual.",
    marco: "Misma familia que Robyn/Meridian, en chico. Es asociación condicionada al modelo, no causalidad: sin experimentos (geo/lift) no prueba incrementalidad.",
    formula: "y = base + tendencia + Σ β·Hill(Adstock(inversión)); ajuste bayesiano (ridge, β ≥ 0) + bootstrap por bloques",
    benchmark: "Meridian considera 'bajo' ~4 datos por parámetro y 'direccional' ~15.",
    funnel: "transversal",
    palancas: [
      { accion: "MMM, atribución e incrementalidad", modulo: "medicion-atribucion" },
      { accion: "Reasignar por retorno marginal", modulo: "reasignacion-inversion" },
    ],
    tipo: "funcion",
  },
  roi_marginal: {
    name: "ROI marginal",
    comoLeer: "Cuánto resultado agrega el <b>próximo</b> peso invertido en un medio, según su curva de respuesta (MMM-lite). Distinto del ROI promedio: un medio puede tener buen ROI promedio y estar saturado.",
    mejorPractica: "Reasigná de medios con ROI marginal bajo a los de ROI marginal alto hasta que se igualen. Leé siempre la banda p10–p90.",
    oportunidad: "Un medio con ROI marginal alto y poca inversión es el candidato a escalar.",
    marco: "Principio de equimarginalidad: el presupuesto está bien repartido cuando el último peso rinde lo mismo en todos los medios.",
    formula: "Δ resultado ÷ Δ inversión en el nivel actual de inversión (derivada de la curva Hill)",
    funnel: "transversal",
    palancas: [{ accion: "Reasignar por retorno marginal", modulo: "reasignacion-inversion" }],
  },
  intensidad_pauta: {
    name: "Intensidad de pauta de la competencia",
    comoLeer: "Meta no publica inversión ni alcance de avisos comerciales en Argentina: se estima con lo observable en la Biblioteca de Anuncios. Índice 0-100 relativo al set (<b>100 = la marca que más pauta</b>).",
    mejorPractica: "Se leen hasta <b>40 avisos activos por marca</b>. Si una marca llega a ese tope, sus avisos se estiman con las versiones por creativo que informa Meta (collation) o su índice es un mínimo (≥). Los avisos se asignan por Página de Facebook o por nombre de página con palabra completa.",
    oportunidad: "'Avisos que más sostienen' (más días al aire y versiones) son la mejor pista de qué mensaje les rinde a los competidores.",
    marco: "Share of voice aproximado: en ausencia de inversión declarada, la actividad publicitaria visible es el mejor proxy de presión competitiva.",
    formula: "Índice = 100 × (35% activos + 20% mensajes distintos + 20% lanzados en 30 días + 15% sostenidos 30+ días + 10% plataformas), cada uno ÷ máximo del set",
    funnel: "awareness",
    palancas: [
      { accion: "Leer la competencia", modulo: "investigacion-competencia" },
      { accion: "Creatividades que funcionan", modulo: "creatividades" },
    ],
    tipo: "funcion",
  },

  // ── Redes (/redes) ── lib/ig-stories.ts, redes-contenido.ts, redes-competencia.ts, redes-temas.ts, fb-paid.ts
  stories_ig: {
    name: "Stories de Instagram",
    comoLeer: "Las Stories se leen cada 6 h mientras están vivas (24 h) y se guarda el <b>máximo</b> visto: el alcance es un piso. Barras = mediana de alcance por Story del mes.",
    mejorPractica: "Leé la <b>tasa de salida</b> (salidas ÷ vistas) y la de <b>respuesta</b> (respuestas ÷ alcance): una secuencia con mucha salida cansa. No entran en el ER por pieza ni en los formatos (su interacción no se mide igual).",
    oportunidad: "Stories con respuestas altas son conversación directa: usalas para encuestas, preguntas de producto y derivar a la tienda.",
    marco: "Las Stories sostienen frecuencia con la comunidad actual; el feed y los Reels son los que suman alcance nuevo.",
    formula: "Tasa de salida = salidas ÷ vistas. Tasa de respuesta = respuestas ÷ alcance",
    funnel: "fidelizacion",
    palancas: [{ accion: "Estrategia de contenido orgánico", modulo: "contenido-organico" }],
    tipo: "funcion",
  },
  formatos_horarios: {
    name: "Formatos y horarios propios",
    comoLeer: "Rendimiento de cada red y formato con posts orgánicos <b>maduros</b> (Instagram 7+ días, Facebook 60+ días: el alcance es lifetime y madura), sin Stories ni posts pautados. <b>Índice 100</b> = mediana de la cuenta en esa red.",
    mejorPractica: "El mapa de día × franja (hora AR) controla por formato: cada post se mide contra la mediana de su red y formato. Solo se muestra con ≥20 posts maduros; la 'mejor celda' exige ≥3 posts (* = menos de 3). Formatos con menos de 5 posts = muestra chica.",
    oportunidad: "Mové el calendario hacia el formato y la franja con índice sostenido &gt;120; no reacciones a una celda con 1-2 posts.",
    marco: "Usar medianas y posts maduros evita que un viral o un post de ayer distorsionen la lectura.",
    formula: "Índice ER = mediana ER del formato ÷ mediana ER de la red × 100. ER = interacciones ÷ alcance del post",
    funnel: "consideracion",
    palancas: [
      { accion: "Estrategia de contenido orgánico", modulo: "contenido-organico" },
      { accion: "Creatividad nativa del formato", modulo: "creatividades" },
    ],
    tipo: "funcion",
  },
  er_comparable: {
    name: "ER comparable (competencia)",
    comoLeer: "Engagement por seguidor de cada marca medido a la <b>misma edad</b> del post, para que la comparación sea justa: un post de ayer todavía no juntó sus interacciones y uno de hace 3 semanas sí.",
    mejorPractica: "Método por marca: <b>°</b> = foto a los 7 días de publicado (si hay ≥3 posts fotografiados, seguidores de ese momento); sin marca = mediana de posts con 7+ días; <b>*</b> = preliminar (pocos posts maduros). Es mediana, no promedio: un sorteo viral inflaba el promedio ~100×.",
    oportunidad: "Una brecha de ER sostenida contra un competidor del mismo tamaño apunta a contenido o formato, no a audiencia.",
    marco: "Comparar a igual edad y con medianas es la condición mínima para un benchmark de redes honesto.",
    formula: "ER = (likes + comentarios) ÷ seguidores; mediana de los posts con ≥7 días (o de la foto a 7 días)",
    funnel: "consideracion",
    palancas: [{ accion: "Leer redes y competencia", modulo: "lectura-redes" }],
    tipo: "funcion",
  },
  pauta_probable: {
    name: "Pauta probable de la competencia",
    comoLeer: "No hay dato cierto de pauta ajena: se marca un post como probablemente impulsado cuando tiene muchas más vistas que lo normal para su marca y red con proporcionalmente poca interacción.",
    mejorPractica: "Regla: views ≥ <b>3×</b> la mediana de su marca y red y ≤ <b>1/3</b> de su interacción por view; <b>alta</b> = ≥5× y ≤1/5, o marcado como patrocinado por el scraper. Mínimo 8 posts con views por marca y red. Es una probabilidad, nunca un hecho.",
    oportunidad: "Los posts que la competencia elige impulsar dicen qué producto o mensaje prioriza este mes.",
    marco: "Inferencia por patrón: el alcance pago rompe la relación habitual entre vistas e interacción.",
    formula: "Probable si views ÷ mediana(views) ≥ 3 y (interacción/view) ÷ mediana ≤ 1/3",
    funnel: "awareness",
    palancas: [{ accion: "Investigación de competencia", modulo: "investigacion-competencia" }],
    tipo: "funcion",
  },
  temas_marca: {
    name: "Temas por marca",
    comoLeer: "Cada post recibe un tema corto (1-3 palabras) por clasificación automática diaria (reusando los temas ya usados). Share = % de los posts de la marca con ese tema; ER = mediana de engagement por seguidor.",
    mejorPractica: "Los 'temas que rinden en la competencia y Drean casi no usa' exigen ≥4 posts de ≥2 marcas, ER ≥1,2× la mediana rival y menos de 5% de los posts propios.",
    oportunidad: "Un tema con ER alto en varios competidores es una hipótesis de contenido barata de probar.",
    marco: "Análisis de gaps de contenido: qué conversación ocupa la categoría y cuál no ocupás.",
    formula: "Gap si ER mediana del tema ≥ 1,2 × mediana rival y share propio < 5%",
    funnel: "consideracion",
    palancas: [{ accion: "Estrategia de contenido orgánico", modulo: "contenido-organico" }],
    tipo: "funcion",
  },
  fb_organico_pago: {
    name: "Facebook orgánico vs pago",
    comoLeer: "Meta deprecó el reach orgánico de Facebook (jun-2026) y el alcance nuevo no separa pago de orgánico. El tablero excluye del orgánico los posts pautados: los que la API marca con <b>≥50% de vistas pagas</b> (post_media_view por is_from_ads) <b>o</b> los que la heurística detecta (alcance &gt; 20.000 con reacciones/alcance &lt; 1%).",
    mejorPractica: "La heurística nunca se apaga: la API solo suma posts pautados, no 'destapa' uno ya filtrado. El reach de la Página no puede superar la suma de los posts orgánicos; si lo supera, se usa la suma.",
    oportunidad: "Por eso la meta del plan Redes se mide con Instagram. Usá Facebook para leer tendencia y contenido, no para fijar metas de alcance.",
    marco: "Un orgánico contaminado por pauta hace creer que el contenido rinde más de lo que rinde.",
    formula: "Pago si vistas pagas ÷ (pagas + orgánicas) ≥ 0,5, o reach > 20k y reacciones ÷ reach < 1%",
    funnel: "consideracion",
    palancas: [{ accion: "Leer redes: engagement de valor", modulo: "lectura-redes" }],
    tipo: "funcion",
  },

  // ── Web (/web) ── lib/web-forecast.ts, web-consent.ts, web-calidad.ts
  cierre_mes_web: {
    name: "Cierre proyectado del mes (web)",
    comoLeer: "Proyecta transacciones e ingresos del mes en curso: ritmo de los últimos 14 días desestacionalizado por día de semana (perfil de las 8 semanas previas) × los días que faltan, más lo ya vendido.",
    mejorPractica: "El rango p10–p90 sale de cómo se equivocó este mismo método en semanas previas (bootstrap por bloques de 7 días). Con menos de 5 días del mes o menos de 14 de historia es <b>preliminar</b> (sin rango). Si la meta cae dentro del rango, estás en línea.",
    oportunidad: "Mirá 'lo que hace falta por día' contra el ritmo actual: si la brecha es grande, se necesita una acción (promo, pauta de conversión), no esperar.",
    marco: "Pace-to-goal diario: anticipar el cierre deja margen para intervenir antes de que el mes termine.",
    formula: "Cierre = real a la fecha + Σ días restantes (ritmo × factor del día de semana)",
    funnel: "conversion",
    palancas: [
      { accion: "Corregir el embudo", modulo: "web-cro" },
      { accion: "Campañas estacionales", modulo: "campanas-estacionales" },
    ],
    tipo: "funcion",
  },
  consent: {
    name: "Medición y consentimiento",
    comoLeer: "Chequeo indirecto: GA4 no informa por API si hay Consent Mode ni cuánta gente rechaza cookies. Se comparan las sesiones que GA4 atribuye a Google Ads (google / cpc) con los clicks que informa Google Ads el mismo mes cerrado.",
    mejorPractica: "Con medición sana GA4 ve <b>~75–100%</b> de los clicks. &lt;75% = parte de los clicks no llega; &lt;50% = GA4 ve menos de la mitad; una <b>caída</b> a menos del 70% de la relación típica (con pauta estable) = cambio en el sitio. Mínimo 300 clicks en el mes.",
    oportunidad: "Revisá etiquetado automático (gclid), pasá Consent Mode a avanzado si hay banner y probá las landings con Tag Assistant: todo lo que GA4 no ve subestima conversión y ROAS.",
    marco: "Sin medición completa, cualquier optimización se hace sobre una muestra sesgada.",
    formula: "% registrado = sesiones GA4 google/cpc ÷ clicks Google Ads (mes cerrado)",
    benchmark: "Sano 75–100%.",
    funnel: "conversion",
    palancas: [{ accion: "Configurar GA4 y eventos clave", modulo: "ga4-configuracion" }],
    tipo: "funcion",
  },
  calidad_ga4: {
    name: "Calidad del dato (GA4)",
    comoLeer: "Checklist del tracking de los últimos 28 días: conversiones medidas, evento purchase con valor y moneda y sin duplicados, pasos de ecommerce, landing identificada, atribución de canal, muestreo, umbrales de privacidad y fila (other). Sello: <b>confiable</b> (sin fallas ni avisos), <b>con advertencias</b> o <b>incompleto</b> (alguna falla).",
    mejorPractica: "'(not set)' en landing o canal 'Unassigned': ≥5% es aviso, ≥20% es falla. Purchase &gt;1,2× las transacciones = se dispara de más. Cada punto trae 'cómo arreglarlo'.",
    oportunidad: "Arreglar el tracking vuelve confiables todos los números de este tablero: es la primera acción si el sello no está en verde.",
    marco: "Garbage in, garbage out: la calidad del dato va antes que el análisis.",
    formula: "Sello = incompleto si hay fallas · con advertencias si hay avisos · confiable si no",
    funnel: "conversion",
    palancas: [
      { accion: "GA4: eventos clave y ecommerce", modulo: "ga4-configuracion" },
      { accion: "UTM y nomenclatura", modulo: "utm-nomenclatura" },
    ],
    tipo: "funcion",
  },
  embudo_ecommerce: {
    name: "Embudo de ecommerce",
    comoLeer: "Usuarios que llegan a cada paso (vio producto → carrito → checkout → compra) en los últimos 28 días (azul) vs los 28 previos (gris). La tasa es el % que pasa desde el paso anterior.",
    mejorPractica: "La 'mayor caída' es el paso con peor variación en puntos vs el período anterior (con ≥50 usuarios de base) y estima las compras perdidas. Un paso en 0 entre dos con datos = falta tracking, no abandono.",
    oportunidad: "Atacá el paso que más cayó antes de traer más tráfico: arreglar una fuga rinde sobre todo el tráfico que ya pagaste.",
    marco: "Teoría de restricciones: la etapa más débil gobierna el resultado del embudo.",
    formula: "Tasa paso = usuarios del paso ÷ usuarios del paso anterior. Compras perdidas ≈ usuarios previos × (tasa previa − actual) × conversión del resto",
    funnel: "conversion",
    palancas: [{ accion: "Web, CRO y embudo", modulo: "web-cro" }],
    tipo: "funcion",
  },
  trafico_ia: {
    name: "Tráfico desde asistentes de IA",
    comoLeer: "Sesiones que llegan desde ChatGPT, Gemini, Perplexity, Copilot, Claude y otros (fuente de la sesión en GA4), su peso en el sitio y cómo convierten contra el promedio.",
    mejorPractica: "Leelo junto a 'Visibilidad en IA' del tablero SEO: la visibilidad es cuánto te nombran; esto es cuánto tráfico te mandan. Conversión = compras (o eventos clave si no hay ecommerce) ÷ sesiones.",
    oportunidad: "Si convierte mejor que el promedio, vale invertir en ser citado (fichas con specs, comparativas, FAQs).",
    marco: "Los asistentes de IA son un canal de descubrimiento nuevo: todavía chico, crece rápido.",
    formula: "Share = sesiones desde IA ÷ sesiones del sitio",
    funnel: "consideracion",
    palancas: [{ accion: "SEO y Share of Search", modulo: "seo-share-of-search" }],
    tipo: "funcion",
  },
  landings_caida: {
    name: "Páginas de entrada en caída",
    comoLeer: "Landings que perdieron sesiones contra los 28 días previos y cayeron bastante más que el sitio (no es la caída general).",
    mejorPractica: "Criterio: caída ≥30%, al menos 20 puntos peor que el sitio, y base previa ≥ máx(50 sesiones, 1% del sitio). Ordenadas por sesiones perdidas.",
    oportunidad: "Cruzalo con 'Contenido que decae' de Search Console y con la pauta: una landing que cae por SEO o por un link roto se recupera rápido.",
    marco: "Detección por excepción: aislar lo que se mueve distinto del total.",
    formula: "Δ = sesiones actuales ÷ previas − 1; entra si Δ ≤ −30% y Δ − Δ sitio ≤ −20 pp",
    funnel: "conversion",
    palancas: [
      { accion: "Search Console: diagnóstico", modulo: "search-console" },
      { accion: "Web y CRO", modulo: "web-cro" },
    ],
    tipo: "funcion",
  },

  // ── SEO / GEO (/seo-search) ── lib/marca-indices.ts, llmo-stats.ts, sc-deep.ts, seo-audit-core.ts, ctr-curve.ts
  salud_digital: {
    name: "Salud digital de marca",
    comoLeer: "Índice relativo al set competitivo con lo que se mide todos los meses sin encuesta: Share of Search, Share of engagement, Visibilidad en IA e Índice de posición SEO (invertido). <b>50 = promedio del set</b>, ±10 = ±1 desvío.",
    mejorPractica: "Mirá qué componente te empuja o te frena (vs el set en σ). Requiere ≥3 marcas y ≥2 componentes; el mes de referencia es el de más componentes entre los 3 últimos.",
    oportunidad: "Un índice que sube antes que Kantar anticipa la próxima ola; si baja, reforzá el componente más débil.",
    marco: "Señal viva de salud de marca entre olas de Kantar: conductual, no declarativa.",
    formula: "Índice = 50 + 10 × promedio de z por componente; z = (valor − promedio del set) ÷ desvío",
    funnel: "awareness",
    palancas: [
      { accion: "Posicionamiento y salud de marca", modulo: "salud-de-marca" },
      { accion: "SEO y Share of Search", modulo: "seo-share-of-search" },
    ],
  },
  esos: {
    name: "ESoS (share of search excedente)",
    comoLeer: "Diferencia entre tu share of search (promedio móvil 6 meses) y tu share de mercado GfK (año móvil, unidades, segmento Total), por categoría. Positivo = más búsqueda que ventas: el share tiende a subir.",
    mejorPractica: "Señal: <b>≥ +0,5 pp</b> sostenido <b>3+ meses</b> → el share tiende a subir; ≤ −0,5 pp → a bajar. Con 18+ meses se estima el rezago propio (r y pares). Solo meses cerrados.",
    oportunidad: "Una categoría con ESoS negativo sostenido pide reforzar awareness y SEO antes de que el share lo refleje.",
    marco: "Les Binet (IPA): el share of search anticipa el share de mercado.",
    formula: "ESoS = SoS (prom. 6m) − share de mercado GfK",
    benchmark: "±0,5 pp durante 3+ meses.",
    funnel: "consideracion",
    palancas: [
      { accion: "Share of Search como indicador adelantado", modulo: "seo-share-of-search" },
      { accion: "Balance marca / activación", modulo: "presupuesto-marketing" },
    ],
  },
  llmo_ic: {
    name: "Visibilidad en IA (con margen de error)",
    comoLeer: "Tasa de mención = % de respuestas del asistente (con búsqueda web, Argentina) que nombran a la marca, con su <b>intervalo de confianza de Wilson al 95%</b>. 12 prompts por categoría en 4 intenciones, corrida semanal, se acumulan 28 días de respuestas.",
    mejorPractica: "Antes de leer una diferencia, mirá si los rangos se solapan. <b>Dato insuficiente</b> con menos de 30 respuestas o margen mayor a ±20 pp. La 'posición en la IA' es ruido: la métrica útil es la tasa.",
    oportunidad: "'Fuentes que te faltan' = dominios que la IA cita cuando nombra a competidores y no a Drean: ahí conviene estar (reseñas, comparadores, medios).",
    marco: "Las respuestas de IA son muy volátiles: solo una tasa sobre muchas corridas con su margen es estadísticamente válida.",
    formula: "Tasa = respuestas que mencionan la marca ÷ respuestas; IC Wilson 95%",
    benchmark: "n ≥ 30 y margen ≤ ±20 pp.",
    funnel: "consideracion",
    palancas: [{ accion: "SEO y Share of Search", modulo: "seo-share-of-search" }],
    tipo: "funcion",
  },
  kw_evolucion: {
    name: "Evolución por keyword",
    comoLeer: "Fotos de la SERP de drean.com.ar entre dos fechas: qué keywords entraron o salieron del top-10 y cuántas están en top-3 y top-10. '—' = fuera del top-100.",
    mejorPractica: "Ganadoras/perdedoras = cambio de ≥3 posiciones o entrada/salida del top-10, ponderado por volumen. Leé primero las perdedoras de alto volumen.",
    oportunidad: "Una keyword que salió del top-10 con mucho volumen es la recuperación más rentable (refrescar la página, enlaces internos).",
    marco: "El SEO se gana keyword por keyword; el índice promedio esconde los movimientos que importan.",
    formula: "Δ posición = posición final − inicial (top-100)",
    funnel: "consideracion",
    palancas: [{ accion: "SEO y Share of Search", modulo: "seo-share-of-search" }],
    tipo: "funcion",
  },
  sc_fondo: {
    name: "Search Console a fondo",
    comoLeer: "Tres lecturas sobre los datos propios de Google: <b>canibalización</b> (2+ URLs propias se reparten una búsqueda), <b>contenido que decae</b> (con su causa probable) y <b>mobile vs desktop</b>.",
    mejorPractica: "Canibalización: búsquedas sin marca con ≥200 impresiones en 90 días, posición media 3–20 y la 2ª URL con ≥15%. Decae: −20% de clics vs 90 días previos y −30% interanual (−35% si no hay interanual). Mobile: alerta si rankea ≥2 posiciones peor, si su CTR rinde &lt;70% del de desktop vs lo esperado, o si sus clics caen ≥20% y 15 pp más que desktop.",
    oportunidad: "Consolidar URLs canibalizadas (canonical, redirect o diferenciar contenido) suele subir la posición de la principal. Una página que decae 'por la SERP' (misma posición, menos clics) apunta a Resúmenes de IA: buscá ser citado.",
    marco: "Search Console es la fuente de verdad del SEO orgánico: impresiones y clics reales, no estimados.",
    formula: "Clicks ganables/mes ≈ impresiones × (CTR esperado una posición arriba de la mejor URL − CTR observado) ÷ meses",
    funnel: "consideracion",
    palancas: [{ accion: "Search Console: diagnóstico", modulo: "search-console" }],
    tipo: "funcion",
  },
  ctr_curva: {
    name: "Curva de CTR esperado",
    comoLeer: "CTR orgánico que se espera por posición, para saber si una página rinde lo que su posición promete. Con suficientes búsquedas sin marca se calibra con el <b>CTR propio</b> de Search Console por tramo (1, 2, 3, 4-5, 6-10, 11-20); si no, se usa la referencia AWR jul-2026.",
    mejorPractica: "Referencia sin Resumen IA: pos 1 20% · 2 10,4% · 3 3,9% · 4 1,7% · 5 1,1% · 6 0,7% · 7-20 0,5% · &gt;20 0,1%. Con Resumen IA el top-5 cae (pos 1 9,7%). Un tramo propio necesita ≥15 búsquedas con ≥100 impresiones.",
    oportunidad: "CTR muy por debajo de lo esperado en su posición = título y descripción a mejorar (o un Resumen IA que se lleva el clic).",
    marco: "Hay mucha dispersión entre estudios de CTR: por eso los clics estimados se leen como rango y la curva propia manda.",
    formula: "CTR propio por tramo = Σ clics ÷ Σ impresiones (búsquedas sin marca), suavizado monótono",
    funnel: "consideracion",
    palancas: [{ accion: "Search Console: diagnóstico", modulo: "search-console" }],
    tipo: "funcion",
  },
  auditoria_seo: {
    name: "Auditoría técnica SEO / GEO",
    comoLeer: "Revisión semanal (lunes) de drean.com.ar: indexación, bots de IA en robots.txt, sitemap, títulos/descripciones/H1/canonical/schema, contenido que depende de JavaScript y velocidad. Problemas ordenados por severidad (error, advertencia, aviso) y clics afectados de Search Console.",
    mejorPractica: "Salud técnica = % de páginas auditadas sin errores, −10 por cada error de todo el sitio. <b>'El sitio rechazó al auditor'</b> = las páginas y el robots.txt respondieron 403/5xx aun simulando un navegador: casi siempre un firewall/CDN que bloquea robots, no páginas rotas; no cuenta como error. Google sí lee el sitio (lo confirman Search Console y PageSpeed).",
    oportunidad: "Bloquear a los bots de búsqueda de IA (OAI-SearchBot, Claude-SearchBot, PerplexityBot) te saca de sus respuestas: es lo primero a revisar.",
    marco: "SEO técnico = condición necesaria: el mejor contenido no rankea si no se indexa.",
    formula: "Salud = (páginas sin error ÷ páginas auditadas) × 100 − 10 × errores de sitio",
    funnel: "consideracion",
    palancas: [{ accion: "Search Console: indexación y velocidad", modulo: "search-console" }],
    tipo: "funcion",
  },
  cwv: {
    name: "Core Web Vitals",
    comoLeer: "Velocidad y estabilidad que vive el usuario, en el percentil 75 mobile. <b>LCP</b> = carga del elemento principal; <b>INP</b> = respuesta a la interacción; <b>CLS</b> = saltos visuales.",
    mejorPractica: "Bueno: LCP ≤ 2,5 s · INP ≤ 200 ms · CLS ≤ 0,1. Malo: LCP &gt; 4 s · INP &gt; 500 ms · CLS &gt; 0,25. 'Usuarios reales' = CrUX de la URL (p75 de Chrome, 28 días); 'sitio completo' = CrUX del origen; 'laboratorio' = PageSpeed (una carga simulada, orientativa). Google rankea con el dato real.",
    oportunidad: "LCP malo en landings de pauta encarece cada click: mejorarlo sube conversión y Quality Score a la vez.",
    marco: "Page experience: los CWV son señal de ranking y, sobre todo, de conversión.",
    formula: "p75 mobile de LCP, INP y CLS (CrUX; si no hay, PageSpeed Insights lab)",
    benchmark: "LCP ≤ 2,5 s · INP ≤ 200 ms · CLS ≤ 0,1.",
    funnel: "conversion",
    palancas: [
      { accion: "Corregir velocidad e indexación", modulo: "search-console" },
      { accion: "Web y CRO", modulo: "web-cro" },
    ],
    tipo: "funcion",
  },

  // ── Diagnóstico ── lib/recomendacion.ts
  que_hacer: {
    name: "Qué hacer ahora",
    comoLeer: "Acciones concretas de las señales automáticas y del Diagnóstico IA en un mismo formato: qué hacer, por qué (con números), impacto estimado, confianza, esfuerzo y cómo medirla. Ordenadas por prioridad.",
    mejorPractica: "Prioridad = impacto (1-5) × confianza (alta 1 · media 0,7 · baja 0,4) ÷ esfuerzo (1 horas · 2 días · 3 semanas). Crítica ≥3 · alta ≥1,8 · media ≥0,9. Tomá pocas por ciclo y medilas antes/después en la ventana indicada.",
    oportunidad: "Las de impacto alto y esfuerzo bajo son las victorias rápidas del mes; las críticas con esfuerzo alto van al plan del trimestre.",
    marco: "Del insight a la acción: una recomendación sin dueño, medición ni prioridad no se ejecuta.",
    formula: "Prioridad = impacto × confianza ÷ esfuerzo",
    funnel: "transversal",
    palancas: [
      { accion: "De los insights al plan de acción", modulo: "plan-de-accion" },
      { accion: "Usar el Diagnóstico IA", modulo: "insights-chat" },
    ],
    tipo: "funcion",
  },

  // ── Mis tableros, alertas y copiloto ──
  armame_tablero: {
    name: "Armame el tablero",
    comoLeer: "Pedís en lenguaje natural lo que querés ver y la IA arma los gráficos con tus planillas y los datos del dashboard que tenés permitidos (Plan de Medios, Web, Redes IG, Seguimiento). Nunca se manda la data entera: solo columnas y 8 filas de muestra.",
    mejorPractica: "Sé específico en métrica, corte y período ('inversión por medio y por mes, con el CPM'). Las métricas derivadas usan la fórmula oficial del catálogo (CPM, CTR, CPC, frecuencia, ER). Revisá 'lo que entendí' y ajustá antes de guardar.",
    oportunidad: "Armá una vez el tablero del comité mensual y compartilo por link o envío programado.",
    marco: "Autoservicio de datos con definiciones únicas: todos leen la misma métrica calculada igual.",
    formula: "Pedido → términos mapeados al catálogo de métricas → gráficos validados (si la IA falla, plan de respaldo determinístico)",
    funnel: "transversal",
    palancas: [
      { accion: "De dónde sale cada dato", modulo: "tableros-planilla" },
      { accion: "La revisión mensual", modulo: "reporte-mensual" },
    ],
    tipo: "funcion",
  },
  anotaciones: {
    name: "Anotaciones",
    comoLeer: "Qué pasó y cuándo ('lanzamiento TV', 'corte de stock'). Se marcan con una línea punteada en los gráficos por fecha de Mis tableros y el Diagnóstico IA las usa como contexto para explicar movimientos.",
    mejorPractica: "Anotá lanzamientos, cambios de precio, quiebres de stock, cambios en el sitio o en el tracking: son la causa más común de un salto que el dato solo no explica. Hasta 280 caracteres.",
    oportunidad: "Con anotaciones el Diagnóstico deja de adivinar: puede separar un efecto de campaña de un evento externo.",
    marco: "Memoria del negocio: los datos dicen qué pasó; las anotaciones, por qué.",
    formula: "Anotación = fecha + texto (≤ 280 caracteres), de este tablero o de todos; se dibuja como línea en esa fecha",
    funnel: "transversal",
    palancas: [{ accion: "Usar el Diagnóstico IA", modulo: "insights-chat" }],
    tipo: "funcion",
  },
  compartir_tablero: {
    name: "Compartir y envío programado",
    comoLeer: "Link de <b>solo lectura</b> firmado: quien lo tenga ve el tablero y sus datos sin iniciar sesión ni editar. Vence a los 7, 30 o 90 días; 'Dejar de compartir' lo invalida. El envío programado manda el link por mail (semanal: lunes · mensual: día 1).",
    mejorPractica: "El envío solo va a casillas de los dominios del equipo. Compartí el link con quien necesita ver, no editar (directorio, agencia).",
    oportunidad: "Un envío mensual fijo instala el ritual de revisión sin depender de que alguien arme el reporte.",
    marco: "Un solo número compartido evita versiones distintas del mismo dato.",
    formula: "Token = contenido + firma HMAC; válido si la firma coincide, no venció y no se revocó",
    funnel: "transversal",
    palancas: [{ accion: "La revisión mensual", modulo: "reporte-mensual" }],
    tipo: "funcion",
  },
  umbrales: {
    name: "Umbrales de alerta",
    comoLeer: "Avisos propios sobre el <b>último mes cerrado</b> (un mes parcial nunca dispara): 'supera', 'queda por debajo de', 'cae más de X%' o 'sube más de X%' vs el mes anterior. Usan las mismas series que Mis tableros y llegan como prioridad alta.",
    mejorPractica: "Hasta 10 umbrales; las variaciones van de 1% a 100%. CPM y CPC se calculan sobre los medios con impresiones (el offline no los distorsiona). Poné umbrales en lo que te obliga a actuar, no en todo.",
    oportunidad: "Un umbral de CPM o de caída de sesiones detecta en días lo que una revisión mensual ve tarde.",
    marco: "Gestión por excepción: la atención va a la desviación relevante.",
    formula: "Dispara si valor(mes cerrado) > / < umbral, o si (valor ÷ mes anterior − 1) supera ±X%",
    funnel: "transversal",
    palancas: [{ accion: "Monitoreo y fuentes", modulo: "conectar-fuentes" }],
    tipo: "funcion",
  },
  copiloto_calidad: {
    name: "Calidad del copiloto",
    comoLeer: "Lo que el equipo calificó con 👍/👎 en 'Preguntale a tus datos' (últimos 90 días): % útiles, motivo más frecuente, fuentes con más respuestas malas (mín. 3 calificaciones) y las peores respuestas primero.",
    mejorPractica: "Revisá las 👎 y <b>verificá</b> las buenas (o corregidas): el copiloto las reusa como ejemplo de método en preguntas parecidas (similitud ≥0,4) y <b>siempre vuelve a consultar los números</b>, no copia la respuesta vieja.",
    oportunidad: "Una fuente con mucho 👎 marca una tool a mejorar o una pregunta frecuente para dejar verificada.",
    marco: "Un asistente mejora con feedback explícito y ejemplos curados por el equipo.",
    formula: "% útiles = 👍 ÷ calificaciones",
    funnel: "transversal",
    palancas: [{ accion: "Usar el copiloto para decidir", modulo: "insights-chat" }],
    tipo: "funcion",
  },
};

/** Alias (canon: minúsculas, sin tildes) → clave, para que kpiKnowFor resuelva los títulos de las secciones. */
export const FUNC_ALIASES: Record<string, string[]> = {
  prob_meta: ["cierre proyectado", "probabilidad de meta", "probabilidad de llegar a la meta", "pace to goal"],
  shapley: ["que explica el resultado", "que explica la brecha", "contribucion shapley", "shapley"],
  salud_datos: ["salud de los datos", "confianza en el dato", "frescura de datos"],
  sugerir_metas: ["sugerir metas", "metas sugeridas"],
  validar_mapa: ["validar con mis datos", "validacion de pesos", "tus pesos se sostienen en tus datos"],
  pacing: ["ritmo de inversion", "pacing"],
  fatiga: ["fatiga creativa", "fatiga creativa por pieza"],
  marca_activacion: ["marca vs activacion", "marca activacion", "60 40"],
  moneda_constante: ["pesos constantes", "moneda constante", "moneda de los montos"],
  mmm: ["mmm", "mmm lite", "que aporta cada medio", "que aporta cada medio mmm lite", "marketing mix model"],
  roi_marginal: ["roi marginal"],
  intensidad_pauta: ["indice de intensidad de pauta", "intensidad de pauta"],
  stories_ig: ["stories de instagram", "stories"],
  formatos_horarios: ["formatos y horarios propios", "formatos y horarios", "mejor dia y franja"],
  er_comparable: ["er comparable", "er comp", "engagement mediana"],
  pauta_probable: ["pauta probable de la competencia", "pauta probable"],
  temas_marca: ["temas por marca", "temas de contenido"],
  fb_organico_pago: ["facebook organico vs pago", "organico vs pago"],
  cierre_mes_web: ["cierre proyectado del mes", "cierre del mes"],
  consent: ["medicion y consentimiento", "consent mode", "consentimiento"],
  calidad_ga4: ["calidad del dato", "calidad del dato ga4"],
  embudo_ecommerce: ["embudo de ecommerce", "embudo ecommerce"],
  trafico_ia: ["trafico desde asistentes de ia", "trafico desde ia", "trafico ia"],
  landings_caida: ["paginas de entrada en caida", "landings en caida"],
  salud_digital: ["salud digital de marca", "salud digital de marca y esos", "indice digital"],
  esos: ["share of search vs share de mercado"],
  llmo_ic: ["visibilidad en ia con margen de error", "tasa de mencion"],
  kw_evolucion: ["evolucion por keyword"],
  sc_fondo: ["search console a fondo", "canibalizacion", "contenido que decae", "mobile vs desktop"],
  ctr_curva: ["curva de ctr", "ctr esperado"],
  auditoria_seo: ["auditoria tecnica", "auditoria tecnica seo geo", "salud tecnica"],
  cwv: ["core web vitals", "cwv"],
  que_hacer: ["que hacer ahora", "recomendaciones"],
  armame_tablero: ["armame el tablero"],
  anotaciones: ["anotaciones"],
  compartir_tablero: ["compartir", "link de solo lectura", "envio programado", "envio programado por mail"],
  umbrales: ["tus umbrales", "umbrales"],
  copiloto_calidad: ["calidad del copiloto"],
};
