// Universo de keywords SEO competitivo (extraídas del análisis del usuario).
// Alimenta el SERP-matrix del route seo-sync (posición de cada dominio por keyword).
export interface KwUniverso { keyword: string; categoria: string; volume: number; }
export const KEYWORD_UNIVERSE: KwUniverso[] = [
  { keyword: "cocina", categoria: "cocinas", volume: 60500 },
  { keyword: "anafe", categoria: "cocinas", volume: 22200 },
  { keyword: "cocina electrica", categoria: "cocinas", volume: 18100 },
  { keyword: "cocinas a gas", categoria: "cocinas", volume: 8100 },
  { keyword: "cocinas precios", categoria: "cocinas", volume: 8100 },
  { keyword: "cocinas a gas natural", categoria: "cocinas", volume: 2900 },
  { keyword: "precios de cocinas", categoria: "cocinas", volume: 2400 },
  { keyword: "cocina a gas envasado", categoria: "cocinas", volume: 1900 },
  { keyword: "cocina electrica precio", categoria: "cocinas", volume: 1300 },
  { keyword: "cocinas de acero inoxidable", categoria: "cocinas", volume: 1000 },
  { keyword: "cocinas baratas a precio de fabrica", categoria: "cocinas", volume: 1000 },
  { keyword: "cocina anafe a gas", categoria: "cocinas", volume: 880 },
  { keyword: "cocina electrica anafe", categoria: "cocinas", volume: 880 },
  { keyword: "precios de cocinas a gas", categoria: "cocinas", volume: 880 },
  { keyword: "cocinas en oferta", categoria: "cocinas", volume: 720 },
  { keyword: "cocinas nuevas", categoria: "cocinas", volume: 590 },
  { keyword: "hot sale cocinas", categoria: "cocinas", volume: 590 },
  { keyword: "precio cocinas a gas", categoria: "cocinas", volume: 590 },
  { keyword: "cocinas a gas precios", categoria: "cocinas", volume: 480 },
  { keyword: "cocinas nuevas baratas", categoria: "cocinas", volume: 480 },
  { keyword: "precios de anafes a gas", categoria: "cocinas", volume: 480 },
  { keyword: "cocinas baratas", categoria: "cocinas", volume: 390 },
  { keyword: "cocinas de 50 cm de ancho", categoria: "cocinas", volume: 390 },
  { keyword: "cocinas electricas modernas", categoria: "cocinas", volume: 390 },
  { keyword: "cocinas modelos", categoria: "cocinas", volume: 390 },
  { keyword: "anafe precio", categoria: "cocinas", volume: 320 },
  { keyword: "cocina 50 cm", categoria: "cocinas", volume: 320 },
  { keyword: "cocina anafe con horno", categoria: "cocinas", volume: 320 },
  { keyword: "cocinas a gas natural baratas", categoria: "cocinas", volume: 320 },
  { keyword: "venta de cocinas", categoria: "cocinas", volume: 320 },
  { keyword: "cocinas de 60 cm de ancho", categoria: "cocinas", volume: 260 },
  { keyword: "cocina a gas y electrica", categoria: "cocinas", volume: 260 },
  { keyword: "cocina para gas envasado", categoria: "cocinas", volume: 260 },
  { keyword: "cocinas a gas natural precios", categoria: "cocinas", volume: 260 },
  { keyword: "cocinas en venta", categoria: "cocinas", volume: 260 },
  { keyword: "precio de anafe", categoria: "cocinas", volume: 260 },
  { keyword: "cocina electrica 4 hornallas y horno", categoria: "cocinas", volume: 210 },
  { keyword: "cocinas a gas baratas", categoria: "cocinas", volume: 210 },
  { keyword: "cocinas economicas a gas", categoria: "cocinas", volume: 210 },
  { keyword: "cyber monday cocinas", categoria: "cocinas", volume: 210 },
  { keyword: "precio anafe a gas", categoria: "cocinas", volume: 210 },
  { keyword: "anafes y hornos empotrados", categoria: "cocinas", volume: 170 },
  { keyword: "cocinas de 55 cm de ancho", categoria: "cocinas", volume: 170 },
  { keyword: "cocina nueva precio", categoria: "cocinas", volume: 170 },
  { keyword: "cocinas 12 cuotas sin interes", categoria: "cocinas", volume: 170 },
  { keyword: "cocinas hot sale", categoria: "cocinas", volume: 170 },
  { keyword: "cocinas modernas precios", categoria: "cocinas", volume: 170 },
  { keyword: "ofertas de cocinas", categoria: "cocinas", volume: 170 },
  { keyword: "precios de cocinas a gas natural", categoria: "cocinas", volume: 170 },
  { keyword: "cocina 4 hornallas precio", categoria: "cocinas", volume: 140 },
  { keyword: "cocina 50 cm acero inoxidable", categoria: "cocinas", volume: 110 },
  { keyword: "cocina 50 cm ancho", categoria: "cocinas", volume: 110 },
  { keyword: "cocina artefacto", categoria: "cocinas", volume: 110 },
  { keyword: "cocinas a gas modernas", categoria: "cocinas", volume: 110 },
  { keyword: "cocinas cuotas sin interes", categoria: "cocinas", volume: 110 },
  { keyword: "cocinas de acero inoxidable precios", categoria: "cocinas", volume: 110 },
  { keyword: "mejor marca de cocina argentina", categoria: "cocinas", volume: 110 },
  { keyword: "ofertas de cocinas industriales", categoria: "cocinas", volume: 110 },
  { keyword: "precios cocinas a gas natural", categoria: "cocinas", volume: 110 },
  { keyword: "como sacar valvula de seguridad de cocina", categoria: "cocinas", volume: 90 },
  { keyword: "cuanto mide una cocina a gas", categoria: "cocinas", volume: 90 },
  { keyword: "donde esta el pico del horno de la cocina", categoria: "cocinas", volume: 90 },
  { keyword: "que cocina a gas es mejor", categoria: "cocinas", volume: 90 },
  { keyword: "cocina 2 hornallas con horno gas natural", categoria: "cocinas", volume: 90 },
  { keyword: "cocina 60 cm blanca", categoria: "cocinas", volume: 90 },
  { keyword: "cocina acero", categoria: "cocinas", volume: 90 },
  { keyword: "cocina de gas nueva", categoria: "cocinas", volume: 90 },
  { keyword: "cocinas a gas en argentina", categoria: "cocinas", volume: 90 },
  { keyword: "cocinas descuentos ofertas", categoria: "cocinas", volume: 90 },
  { keyword: "cual es la mejor cocina a gas en argentina", categoria: "cocinas", volume: 90 },
  { keyword: "cyber monday anafes", categoria: "cocinas", volume: 90 },
  { keyword: "venta de anafes electricos", categoria: "cocinas", volume: 90 },
  { keyword: "cocina a gas o electrica argentina", categoria: "cocinas", volume: 70 },
  { keyword: "cocina 53 cm de ancho", categoria: "cocinas", volume: 70 },
  { keyword: "cocina 60 cm de ancho", categoria: "cocinas", volume: 70 },
  { keyword: "cocina a gas 50 cm", categoria: "cocinas", volume: 70 },
  { keyword: "cocinas a gas argentina", categoria: "cocinas", volume: 70 },
  { keyword: "cocinas a gas de 55 cm de ancho", categoria: "cocinas", volume: 70 },
  { keyword: "cocinas a gas natural con horno autolimpiante", categoria: "cocinas", volume: 70 },
  { keyword: "cocinas ahora 18", categoria: "cocinas", volume: 70 },
  { keyword: "cocinas en acero inoxidable precios", categoria: "cocinas", volume: 70 },
  { keyword: "cocinas en cuotas sin interes", categoria: "cocinas", volume: 70 },
  { keyword: "cocinas en oferta precios", categoria: "cocinas", volume: 70 },
  { keyword: "cocinas nuevas a gas", categoria: "cocinas", volume: 70 },
  { keyword: "cuales son las mejores cocinas a gas en argentina", categoria: "cocinas", volume: 70 },
  { keyword: "heladera", categoria: "heladeras", volume: 74000 },
  { keyword: "heladera con congelador", categoria: "heladeras", volume: 49500 },
  { keyword: "heladera con freezer", categoria: "heladeras", volume: 33100 },
  { keyword: "heladeras no frost", categoria: "heladeras", volume: 14800 },
  { keyword: "freezer vertical", categoria: "heladeras", volume: 14800 },
  { keyword: "heladeras precios", categoria: "heladeras", volume: 12100 },
  { keyword: "freezer horizontal", categoria: "heladeras", volume: 6600 },
  { keyword: "heladera bajo mesada", categoria: "heladeras", volume: 6600 },
  { keyword: "freezer chico", categoria: "heladeras", volume: 4400 },
  { keyword: "heladeras con freezer precios", categoria: "heladeras", volume: 3600 },
  { keyword: "precio de heladeras", categoria: "heladeras", volume: 3600 },
  { keyword: "heladera doble puerta", categoria: "heladeras", volume: 2900 },
  { keyword: "freezer precios", categoria: "heladeras", volume: 2900 },
  { keyword: "heladera chica", categoria: "heladeras", volume: 2900 },
  { keyword: "precio de heladeras con freezer", categoria: "heladeras", volume: 2900 },
  { keyword: "heladera con freezer no frost", categoria: "heladeras", volume: 2400 },
  { keyword: "heladera inverter", categoria: "heladeras", volume: 2400 },
  { keyword: "heladera chiquita", categoria: "heladeras", volume: 2400 },
  { keyword: "heladeras con freezer baratas", categoria: "heladeras", volume: 2400 },
  { keyword: "precio de freezer", categoria: "heladeras", volume: 2400 },
  { keyword: "heladera con freezer abajo", categoria: "heladeras", volume: 1900 },
  { keyword: "heladera side by side", categoria: "heladeras", volume: 1900 },
  { keyword: "heladeras con freezer chicas", categoria: "heladeras", volume: 1900 },
  { keyword: "heladeras ofertas", categoria: "heladeras", volume: 1900 },
  { keyword: "que es una heladera ciclica", categoria: "heladeras", volume: 1600 },
  { keyword: "freezer bajo mesada", categoria: "heladeras", volume: 1600 },
  { keyword: "heladera bajo mesada con freezer", categoria: "heladeras", volume: 1600 },
  { keyword: "heladera ciclica", categoria: "heladeras", volume: 1300 },
  { keyword: "heladera dos puertas", categoria: "heladeras", volume: 1300 },
  { keyword: "heladera pequeña", categoria: "heladeras", volume: 1300 },
  { keyword: "heladera sin freezer", categoria: "heladeras", volume: 1300 },
  { keyword: "heladeras baratas", categoria: "heladeras", volume: 1000 },
  { keyword: "heladeras nuevas baratas", categoria: "heladeras", volume: 1000 },
  { keyword: "heladeras no frost inverter", categoria: "heladeras", volume: 880 },
  { keyword: "heladera con freezer grande", categoria: "heladeras", volume: 880 },
  { keyword: "heladeras economicas", categoria: "heladeras", volume: 880 },
  { keyword: "heladeras no frost precios", categoria: "heladeras", volume: 880 },
  { keyword: "freezer vertical chico", categoria: "heladeras", volume: 720 },
  { keyword: "heladeras 18 cuotas sin interes", categoria: "heladeras", volume: 720 },
  { keyword: "heladeras ahora 30", categoria: "heladeras", volume: 720 },
  { keyword: "heladeras cuotas sin interes", categoria: "heladeras", volume: 720 },
  { keyword: "heladeras nuevas", categoria: "heladeras", volume: 720 },
  { keyword: "hot sale heladeras", categoria: "heladeras", volume: 720 },
  { keyword: "heladera gris", categoria: "heladeras", volume: 590 },
  { keyword: "heladeras 12 cuotas sin interes", categoria: "heladeras", volume: 590 },
  { keyword: "heladeras pequeñas con freezer", categoria: "heladeras", volume: 590 },
  { keyword: "ofertas de heladeras", categoria: "heladeras", volume: 590 },
  { keyword: "que es una heladera no frost", categoria: "heladeras", volume: 480 },
  { keyword: "ciber monday heladera", categoria: "heladeras", volume: 480 },
  { keyword: "cyber monday heladeras", categoria: "heladeras", volume: 480 },
  { keyword: "heladeras chicas precios", categoria: "heladeras", volume: 480 },
  { keyword: "heladeras inverter no frost", categoria: "heladeras", volume: 480 },
  { keyword: "heladeras no frost economicas", categoria: "heladeras", volume: 480 },
  { keyword: "precio freezer chicos economicos", categoria: "heladeras", volume: 480 },
  { keyword: "comprar heladera", categoria: "heladeras", volume: 390 },
  { keyword: "freezer inverter", categoria: "heladeras", volume: 390 },
  { keyword: "freezer oferta", categoria: "heladeras", volume: 390 },
  { keyword: "precio freezer vertical", categoria: "heladeras", volume: 390 },
  { keyword: "venta de heladeras", categoria: "heladeras", volume: 390 },
  { keyword: "altura heladera", categoria: "heladeras", volume: 320 },
  { keyword: "freezer 400 litros", categoria: "heladeras", volume: 320 },
  { keyword: "freezer grande", categoria: "heladeras", volume: 320 },
  { keyword: "freezer horizontal chico", categoria: "heladeras", volume: 320 },
  { keyword: "freezer no frost", categoria: "heladeras", volume: 320 },
  { keyword: "freezer pequeño", categoria: "heladeras", volume: 320 },
  { keyword: "heladera bajo mesada precio", categoria: "heladeras", volume: 320 },
  { keyword: "heladera doble", categoria: "heladeras", volume: 320 },
  { keyword: "ofertas heladeras con freezer", categoria: "heladeras", volume: 320 },
  { keyword: "precio de heladeras nuevas", categoria: "heladeras", volume: 320 },
  { keyword: "dimensiones heladera", categoria: "heladeras", volume: 260 },
  { keyword: "heladera ciclica o no frost", categoria: "heladeras", volume: 260 },
  { keyword: "ancho heladera", categoria: "heladeras", volume: 260 },
  { keyword: "combo heladera y cocina", categoria: "heladeras", volume: 260 },
  { keyword: "cuanto sale una heladera", categoria: "heladeras", volume: 260 },
  { keyword: "freezer chico precio", categoria: "heladeras", volume: 260 },
  { keyword: "heladera con dispenser de agua", categoria: "heladeras", volume: 260 },
  { keyword: "heladera con freezer inferior", categoria: "heladeras", volume: 260 },
  { keyword: "heladera dream", categoria: "heladeras", volume: 260 },
  { keyword: "heladera mediana", categoria: "heladeras", volume: 260 },
  { keyword: "heladeras economicas nuevas", categoria: "heladeras", volume: 260 },
  { keyword: "heladeras mar del plata", categoria: "heladeras", volume: 260 },
  { keyword: "precio de freezer chico", categoria: "heladeras", volume: 260 },
  { keyword: "altura de heladera", categoria: "heladeras", volume: 210 },
  { keyword: "ancho de heladeras", categoria: "heladeras", volume: 210 },
  { keyword: "heladera 3 puertas", categoria: "heladeras", volume: 210 },
  { keyword: "heladera blanca", categoria: "heladeras", volume: 210 },
  { keyword: "heladera cocina", categoria: "heladeras", volume: 210 },
  { keyword: "heladera con freezer en oferta", categoria: "heladeras", volume: 210 },
  { keyword: "heladera con freezer inverter", categoria: "heladeras", volume: 210 },
  { keyword: "heladera plateada", categoria: "heladeras", volume: 210 },
  { keyword: "heladera y freezer vertical", categoria: "heladeras", volume: 210 },
  { keyword: "heladeras chicas bajo mesada", categoria: "heladeras", volume: 210 },
  { keyword: "heladeras de acero inoxidable", categoria: "heladeras", volume: 210 },
  { keyword: "heladeras en cuotas", categoria: "heladeras", volume: 210 },
  { keyword: "heladeras en venta", categoria: "heladeras", volume: 210 },
  { keyword: "heladeras no frost rodo", categoria: "heladeras", volume: 210 },
  { keyword: "mejores heladeras argentina", categoria: "heladeras", volume: 210 },
  { keyword: "black friday heladeras", categoria: "heladeras", volume: 170 },
  { keyword: "cuanto sale un freezer", categoria: "heladeras", volume: 170 },
  { keyword: "freezer 120 litros", categoria: "heladeras", volume: 170 },
  { keyword: "freezer 290 litros", categoria: "heladeras", volume: 170 },
  { keyword: "freezer de 400 litros", categoria: "heladeras", volume: 170 },
  { keyword: "freezer nuevo", categoria: "heladeras", volume: 170 },
  { keyword: "freezer vertical bajo mesada", categoria: "heladeras", volume: 170 },
  { keyword: "heladera 400 litros", categoria: "heladeras", volume: 170 },
  { keyword: "heladera ahora 30", categoria: "heladeras", volume: 170 },
  { keyword: "heladera argentina", categoria: "heladeras", volume: 170 },
  { keyword: "heladera con freezer doble puerta", categoria: "heladeras", volume: 170 },
  { keyword: "heladeras ahora 12", categoria: "heladeras", volume: 170 },
  { keyword: "heladeras dream", categoria: "heladeras", volume: 170 },
  { keyword: "heladeras hot sale", categoria: "heladeras", volume: 170 },
  { keyword: "heladeras nuevas precios", categoria: "heladeras", volume: 170 },
  { keyword: "heladeras sin freezer precios", categoria: "heladeras", volume: 170 },
  { keyword: "precios de freezer nuevos", categoria: "heladeras", volume: 170 },
  { keyword: "precios de heladeras no frost", categoria: "heladeras", volume: 170 },
  { keyword: "tecnologia inverter en heladeras", categoria: "heladeras", volume: 170 },
  { keyword: "venta de freezer", categoria: "heladeras", volume: 170 },
  { keyword: "congelador de heladera", categoria: "heladeras", volume: 140 },
  { keyword: "cuanto cuesta una heladera", categoria: "heladeras", volume: 140 },
  { keyword: "freezer horizontal oferta", categoria: "heladeras", volume: 140 },
  { keyword: "freezer vertical con cajones", categoria: "heladeras", volume: 140 },
  { keyword: "freezer vertical inverter", categoria: "heladeras", volume: 140 },
  { keyword: "frigobar con freezer", categoria: "heladeras", volume: 140 },
  { keyword: "heladera en promocion", categoria: "heladeras", volume: 140 },
  { keyword: "heladera familiar con freezer", categoria: "heladeras", volume: 140 },
  { keyword: "heladeras 24 cuotas sin interes", categoria: "heladeras", volume: 140 },
  { keyword: "heladeras con freezer abajo inverter", categoria: "heladeras", volume: 140 },
  { keyword: "heladeras promociones", categoria: "heladeras", volume: 140 },
  { keyword: "cuanto sale una heladera nueva", categoria: "heladeras", volume: 110 },
  { keyword: "freezer 500 litros", categoria: "heladeras", volume: 110 },
  { keyword: "freezer en venta", categoria: "heladeras", volume: 110 },
  { keyword: "freezer no frost vertical", categoria: "heladeras", volume: 110 },
  { keyword: "freezer vertical no frost", categoria: "heladeras", volume: 110 },
  { keyword: "heladera 300 litros", categoria: "heladeras", volume: 110 },
  { keyword: "heladera 360 litros", categoria: "heladeras", volume: 110 },
  { keyword: "heladera 500 litros", categoria: "heladeras", volume: 110 },
  { keyword: "heladera chiquita con freezer", categoria: "heladeras", volume: 110 },
  { keyword: "heladera chiquita precio", categoria: "heladeras", volume: 110 },
  { keyword: "heladera con congelador nueva", categoria: "heladeras", volume: 110 },
  { keyword: "heladera con fabrica de hielo", categoria: "heladeras", volume: 110 },
  { keyword: "heladera con freezer abajo no frost", categoria: "heladeras", volume: 110 },
  { keyword: "heladera cycle defrost", categoria: "heladeras", volume: 110 },
  { keyword: "heladera mediana con freezer", categoria: "heladeras", volume: 110 },
  { keyword: "heladeras 12 cuotas", categoria: "heladeras", volume: 110 },
  { keyword: "heladeras chicas baratas", categoria: "heladeras", volume: 110 },
  { keyword: "heladeras con freezer no frost inverter", categoria: "heladeras", volume: 110 },
  { keyword: "heladeras con freezer nuevas", categoria: "heladeras", volume: 110 },
  { keyword: "heladeras dobles", categoria: "heladeras", volume: 110 },
  { keyword: "heladeras dos puertas con freezer", categoria: "heladeras", volume: 110 },
  { keyword: "ofertas de freezer", categoria: "heladeras", volume: 110 },
  { keyword: "ofertas heladeras no frost", categoria: "heladeras", volume: 110 },
  { keyword: "precio de freezer vertical", categoria: "heladeras", volume: 110 },
  { keyword: "precio de heladeras chicas", categoria: "heladeras", volume: 110 },
  { keyword: "precio de los freezer", categoria: "heladeras", volume: 110 },
  { keyword: "precio freezer chico", categoria: "heladeras", volume: 110 },
  { keyword: "que es inverter en heladeras", categoria: "heladeras", volume: 110 },
  { keyword: "que es tecnologia inverter en heladeras", categoria: "heladeras", volume: 110 },
  { keyword: "que es tecnología inverter en heladeras", categoria: "heladeras", volume: 110 },
  { keyword: "que es una heladera inverter", categoria: "heladeras", volume: 110 },
  { keyword: "que heladera comprar", categoria: "heladeras", volume: 110 },
  { keyword: "resistencia heladera no frost", categoria: "heladeras", volume: 110 },
  { keyword: "venta de heladeras nuevas", categoria: "heladeras", volume: 110 },
  { keyword: "chapa interior de freezer", categoria: "heladeras", volume: 90 },
  { keyword: "combo de cocina y heladera", categoria: "heladeras", volume: 90 },
  { keyword: "combo heladera y lavarropas", categoria: "heladeras", volume: 90 },
  { keyword: "cuanto cuesta un freezer", categoria: "heladeras", volume: 90 },
  { keyword: "freezer 210", categoria: "heladeras", volume: 90 },
  { keyword: "freezer 430 litros", categoria: "heladeras", volume: 90 },
  { keyword: "freezer 500 lts precio", categoria: "heladeras", volume: 90 },
  { keyword: "freezer black friday", categoria: "heladeras", volume: 90 },
  { keyword: "freezer de 80 litros", categoria: "heladeras", volume: 90 },
  { keyword: "freezer de pequeño", categoria: "heladeras", volume: 90 },
  { keyword: "freezer heladera horizontal", categoria: "heladeras", volume: 90 },
  { keyword: "freezer horizontal precios", categoria: "heladeras", volume: 90 },
  { keyword: "freezer vertical 120 litros", categoria: "heladeras", volume: 90 },
  { keyword: "freezer vertical no frost inverter", categoria: "heladeras", volume: 90 },
  { keyword: "heladera 120 litros", categoria: "heladeras", volume: 90 },
  { keyword: "heladera 24 cuotas", categoria: "heladeras", volume: 90 },
  { keyword: "heladera bajo mesada negra", categoria: "heladeras", volume: 90 },
  { keyword: "heladera chica con freezer precios", categoria: "heladeras", volume: 90 },
  { keyword: "heladera con", categoria: "heladeras", volume: 90 },
  { keyword: "heladera con freezer 12 cuotas sin interes", categoria: "heladeras", volume: 90 },
  { keyword: "heladera frost", categoria: "heladeras", volume: 90 },
  { keyword: "heladera inverter hot sale", categoria: "heladeras", volume: 90 },
  { keyword: "heladera o freezer", categoria: "heladeras", volume: 90 },
  { keyword: "heladera sin freezer chica", categoria: "heladeras", volume: 90 },
  { keyword: "heladeras angostas no frost", categoria: "heladeras", volume: 90 },
  { keyword: "heladeras baratas argentina", categoria: "heladeras", volume: 90 },
  { keyword: "heladeras ciclicas con freezer", categoria: "heladeras", volume: 90 },
  { keyword: "heladeras comerciales precios", categoria: "heladeras", volume: 90 },
  { keyword: "heladeras de mas de 500 litros", categoria: "heladeras", volume: 90 },
  { keyword: "marca de heladeras buenas", categoria: "heladeras", volume: 90 },
  { keyword: "ofertas de freezer horizontal", categoria: "heladeras", volume: 90 },
  { keyword: "ofertas de heladeras nuevas", categoria: "heladeras", volume: 90 },
  { keyword: "precio de freezer vertical con cajones", categoria: "heladeras", volume: 90 },
  { keyword: "precio de heladera con congelador", categoria: "heladeras", volume: 90 },
  { keyword: "precio heladera dos puertas", categoria: "heladeras", volume: 90 },
  { keyword: "rodo heladeras inverter", categoria: "heladeras", volume: 90 },
  { keyword: "valor de freezer vertical", categoria: "heladeras", volume: 90 },
  { keyword: "venta de heladeras con freezer", categoria: "heladeras", volume: 90 },
  { keyword: "cual es la mejor heladera con freezer en argentina", categoria: "heladeras", volume: 70 },
  { keyword: "cual es la mejor heladera no frost en argentina", categoria: "heladeras", volume: 70 },
  { keyword: "cuotas sin interes heladeras", categoria: "heladeras", volume: 70 },
  { keyword: "freezer 112 litros", categoria: "heladeras", volume: 70 },
  { keyword: "freezer 12 cuotas sin interes", categoria: "heladeras", volume: 70 },
  { keyword: "freezer 220 litros", categoria: "heladeras", volume: 70 },
  { keyword: "freezer 280 litros", categoria: "heladeras", volume: 70 },
  { keyword: "freezer 400", categoria: "heladeras", volume: 70 },
  { keyword: "freezer chico bajo mesada", categoria: "heladeras", volume: 70 },
  { keyword: "freezer gris", categoria: "heladeras", volume: 70 },
  { keyword: "heladera 320 litros", categoria: "heladeras", volume: 70 },
  { keyword: "heladera bajo mesada inverter", categoria: "heladeras", volume: 70 },
  { keyword: "heladera con freezer acero inoxidable", categoria: "heladeras", volume: 70 },
  { keyword: "heladera de 360 litros", categoria: "heladeras", volume: 70 },
  { keyword: "heladera mas barata", categoria: "heladeras", volume: 70 },
  { keyword: "heladera no frost cuotas sin interes", categoria: "heladeras", volume: 70 },
  { keyword: "heladeras 60 cm de ancho", categoria: "heladeras", volume: 70 },
  { keyword: "heladeras de acero inoxidable no frost", categoria: "heladeras", volume: 70 },
  { keyword: "heladeras de dos puertas precios", categoria: "heladeras", volume: 70 },
  { keyword: "heladeras en venta nuevas", categoria: "heladeras", volume: 70 },
  { keyword: "heladeras inverter a++", categoria: "heladeras", volume: 70 },
  { keyword: "inverter en heladeras", categoria: "heladeras", volume: 70 },
  { keyword: "mejores heladeras con freezer", categoria: "heladeras", volume: 70 },
  { keyword: "precio de una heladera con freezer", categoria: "heladeras", volume: 70 },
  { keyword: "precio heladeras con freezer no frost", categoria: "heladeras", volume: 70 },
  { keyword: "que freezer comprar", categoria: "heladeras", volume: 70 },
  { keyword: "que heladera comprar en argentina", categoria: "heladeras", volume: 70 },
  { keyword: "sale agua de la heladera", categoria: "heladeras", volume: 70 },
  { keyword: "venta de freezer en mar del plata", categoria: "heladeras", volume: 70 },
  { keyword: "venta de freezer nuevos", categoria: "heladeras", volume: 70 },
  { keyword: "lavarropas", categoria: "lavarropas", volume: 60500 },
  { keyword: "lavarropas automatico", categoria: "lavarropas", volume: 60500 },
  { keyword: "secarropas", categoria: "lavarropas", volume: 14800 },
  { keyword: "lavarropas automaticos precios", categoria: "lavarropas", volume: 12100 },
  { keyword: "lavasecarropas", categoria: "lavarropas", volume: 9900 },
  { keyword: "lavarropas carga superior", categoria: "lavarropas", volume: 5400 },
  { keyword: "secarropas precios", categoria: "lavarropas", volume: 3600 },
  { keyword: "precios de lavarropas automaticos", categoria: "lavarropas", volume: 2900 },
  { keyword: "lavarropas automatico carga superior", categoria: "lavarropas", volume: 2400 },
  { keyword: "lavarropas automaticos baratos", categoria: "lavarropas", volume: 2400 },
  { keyword: "ofertas lavarropas automaticos", categoria: "lavarropas", volume: 2400 },
  { keyword: "lavarropas carga frontal", categoria: "lavarropas", volume: 1900 },
  { keyword: "medidas lavarropas", categoria: "lavarropas", volume: 1900 },
  { keyword: "lavarropas precios", categoria: "lavarropas", volume: 1900 },
  { keyword: "lavarropas comun", categoria: "lavarropas", volume: 1600 },
  { keyword: "precio de lavarropas", categoria: "lavarropas", volume: 1600 },
  { keyword: "precio de secarropas", categoria: "lavarropas", volume: 1600 },
  { keyword: "lavarropas inverter", categoria: "lavarropas", volume: 1300 },
  { keyword: "lavarropas ofertas", categoria: "lavarropas", volume: 1300 },
  { keyword: "medidas de lavarropas", categoria: "lavarropas", volume: 1000 },
  { keyword: "hot sale lavarropas", categoria: "lavarropas", volume: 880 },
  { keyword: "hot sale lavasecarropas", categoria: "lavarropas", volume: 880 },
  { keyword: "lavarropas automático precios", categoria: "lavarropas", volume: 880 },
  { keyword: "lavarropas 10 kg", categoria: "lavarropas", volume: 720 },
  { keyword: "lavarropas automatico carga frontal", categoria: "lavarropas", volume: 590 },
  { keyword: "lavarropas 12 cuotas sin interes", categoria: "lavarropas", volume: 590 },
  { keyword: "lavarropas chico", categoria: "lavarropas", volume: 590 },
  { keyword: "lavarropas frontal", categoria: "lavarropas", volume: 480 },
  { keyword: "lavarropas 8 kg", categoria: "lavarropas", volume: 480 },
  { keyword: "lavarropas ahora 30", categoria: "lavarropas", volume: 480 },
  { keyword: "lavarropas comun precio", categoria: "lavarropas", volume: 480 },
  { keyword: "secaropa", categoria: "lavarropas", volume: 480 },
  { keyword: "lavarropas 18 cuotas sin interes", categoria: "lavarropas", volume: 390 },
  { keyword: "lavarropas carga frontal medidas", categoria: "lavarropas", volume: 390 },
  { keyword: "lavarropas carga superior 10 kg", categoria: "lavarropas", volume: 390 },
  { keyword: "lavarropas cuotas sin interes", categoria: "lavarropas", volume: 390 },
  { keyword: "lavarropas pequeños", categoria: "lavarropas", volume: 390 },
  { keyword: "lavarropas tambor", categoria: "lavarropas", volume: 390 },
  { keyword: "lavasecarropas inverter", categoria: "lavarropas", volume: 390 },
  { keyword: "ofertas de lavarropas", categoria: "lavarropas", volume: 390 },
  { keyword: "ahora 30 lavarropas", categoria: "lavarropas", volume: 320 },
  { keyword: "cuanto sale un lavarropas automatico", categoria: "lavarropas", volume: 320 },
  { keyword: "cyber monday lavarropas", categoria: "lavarropas", volume: 320 },
  { keyword: "lavarropa semiautomatico como funciona", categoria: "lavarropas", volume: 320 },
  { keyword: "lavarropas de 10 kg", categoria: "lavarropas", volume: 320 },
  { keyword: "lavarropas next", categoria: "lavarropas", volume: 320 },
  { keyword: "medidas de lavarropas automaticos", categoria: "lavarropas", volume: 320 },
  { keyword: "precio de lavarropas comunes", categoria: "lavarropas", volume: 320 },
  { keyword: "que es un lavarropas semiautomatico", categoria: "lavarropas", volume: 320 },
  { keyword: "lavarropas chico para departamento", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas con wifi", categoria: "lavarropas", volume: 260 },
  { keyword: "cuanto pesa un lavarropas", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas 13 kg carga superior", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas 6kg", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas 8 kg carga superior", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas 9 kg", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas automatico 10 kg", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas automatico 8 kg", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas baratos", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas economicos", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas hot sale", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas nuevos", categoria: "lavarropas", volume: 260 },
  { keyword: "lavarropas pequeño", categoria: "lavarropas", volume: 260 },
  { keyword: "secarropas baratos", categoria: "lavarropas", volume: 260 },
  { keyword: "venta de lavarropas", categoria: "lavarropas", volume: 260 },
  { keyword: "que es inverter en lavarropas", categoria: "lavarropas", volume: 210 },
  { keyword: "comprar lavarropas", categoria: "lavarropas", volume: 210 },
  { keyword: "cual es la mejor marca de lavarropas", categoria: "lavarropas", volume: 210 },
  { keyword: "lavarropas 12 kg", categoria: "lavarropas", volume: 210 },
  { keyword: "lavarropas 8 kg carga frontal", categoria: "lavarropas", volume: 210 },
  { keyword: "lavarropas automatico chico", categoria: "lavarropas", volume: 210 },
  { keyword: "lavarropas chico carga frontal", categoria: "lavarropas", volume: 210 },
  { keyword: "lavarropas vertical", categoria: "lavarropas", volume: 210 },
  { keyword: "lavasecarropas 12 kg", categoria: "lavarropas", volume: 210 },
  { keyword: "lavasecarropas automatico", categoria: "lavarropas", volume: 210 },
  { keyword: "tecnologia inverter lavarropas", categoria: "lavarropas", volume: 210 },
  { keyword: "dimensiones lavarropas", categoria: "lavarropas", volume: 170 },
  { keyword: "que lavarropas comprar", categoria: "lavarropas", volume: 170 },
  { keyword: "como limpiar lavarropa automatico", categoria: "lavarropas", volume: 170 },
  { keyword: "cuanto cuesta un lavarropa automatico", categoria: "lavarropas", volume: 170 },
  { keyword: "cuanto sale un secarropas", categoria: "lavarropas", volume: 170 },
  { keyword: "lavaropa automatico", categoria: "lavarropas", volume: 170 },
  { keyword: "lavarropas 7 kg", categoria: "lavarropas", volume: 170 },
  { keyword: "lavarropas automatico 5 kg", categoria: "lavarropas", volume: 170 },
  { keyword: "lavarropas automático 5 kg", categoria: "lavarropas", volume: 170 },
  { keyword: "lavarropas automaticos baratos nuevos", categoria: "lavarropas", volume: 170 },
  { keyword: "lavarropas automaticos economicos", categoria: "lavarropas", volume: 170 },
  { keyword: "lavarropas carga superior 6 kg", categoria: "lavarropas", volume: 170 },
  { keyword: "lavarropas carga vertical", categoria: "lavarropas", volume: 170 },
  { keyword: "lavarropas de 8 kilos", categoria: "lavarropas", volume: 170 },
  { keyword: "lavarropas de carga superior", categoria: "lavarropas", volume: 170 },
  { keyword: "lavasecarropas carga superior", categoria: "lavarropas", volume: 170 },
  { keyword: "mejores lavarropas", categoria: "lavarropas", volume: 170 },
  { keyword: "secarropas automatico", categoria: "lavarropas", volume: 170 },
  { keyword: "secarropas automático", categoria: "lavarropas", volume: 170 },
  { keyword: "lavasecarropas precios", categoria: "lavarropas", volume: 140 },
  { keyword: "que es mejor lavarropas carga superior o frontal", categoria: "lavarropas", volume: 140 },
  { keyword: "cuanto sale un lavarropas", categoria: "lavarropas", volume: 140 },
  { keyword: "dream lavarropa", categoria: "lavarropas", volume: 140 },
  { keyword: "lavarropas 40 cm ancho", categoria: "lavarropas", volume: 140 },
  { keyword: "lavarropas ahora 12", categoria: "lavarropas", volume: 140 },
  { keyword: "lavarropas automatico medidas", categoria: "lavarropas", volume: 140 },
  { keyword: "lavarropas en 12 cuotas sin interés", categoria: "lavarropas", volume: 140 },
  { keyword: "lavarropas gris", categoria: "lavarropas", volume: 140 },
  { keyword: "lavarropas negro", categoria: "lavarropas", volume: 140 },
  { keyword: "lavarropas tambor vertical", categoria: "lavarropas", volume: 140 },
  { keyword: "que es tecnologia inverter en lavarropas", categoria: "lavarropas", volume: 140 },
  { keyword: "sistema de lavado europeo", categoria: "lavarropas", volume: 140 },
  { keyword: "tecnologia inverter en lavarropas", categoria: "lavarropas", volume: 140 },
  { keyword: "venta lavarropas", categoria: "lavarropas", volume: 140 },
  { keyword: "ancho lavarropas", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas 12 cuotas sin interés", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas 15 kg", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas automatico 6 kg", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas automatico de 10 kg", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas automatico inverter", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas automaticos de 12 kg", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas baratos nuevos", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas carga frontal pequeño", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas carga superior medidas", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas de 15 kg", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas en cuotas", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas la plata", categoria: "lavarropas", volume: 110 },
  { keyword: "lavarropas pequeños carga frontal", categoria: "lavarropas", volume: 110 },
  { keyword: "lavasecarropas ofertas", categoria: "lavarropas", volume: 110 },
  { keyword: "medidas lavarropas automatico", categoria: "lavarropas", volume: 110 },
  { keyword: "que es un lavarropas inverter", categoria: "lavarropas", volume: 110 },
  { keyword: "que marca de lavarropas es mejor en argentina", categoria: "lavarropas", volume: 110 },
  { keyword: "secarropa oferta", categoria: "lavarropas", volume: 110 },
  { keyword: "secarropas inverter", categoria: "lavarropas", volume: 110 },
  { keyword: "secarropas ofertas", categoria: "lavarropas", volume: 110 },
  { keyword: "tipo de lavarropas", categoria: "lavarropas", volume: 110 },
  { keyword: "venta de lavarropas automaticos", categoria: "lavarropas", volume: 110 },
  { keyword: "comprar lavarropas automatico", categoria: "lavarropas", volume: 90 },
  { keyword: "hot sale lavarropas carga superior", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas 1000 rpm", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas 1200 rpm", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas 15 kg carga superior", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas 40 cm", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas 6 kg carga frontal", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas altura 80 cm", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas automatico 12 cuotas sin interes", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas automatico 7 kg", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas automatico frontal", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas automatico gris", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas buenos aires", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas carga frontal bajo mesada", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas de 13 kilos", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas ofertas cuotas sin interes", categoria: "lavarropas", volume: 90 },
  { keyword: "lavarropas pequeños medidas", categoria: "lavarropas", volume: 90 },
  { keyword: "ofertas de lavarropas automaticos", categoria: "lavarropas", volume: 90 },
  { keyword: "precio de los lavarropas", categoria: "lavarropas", volume: 90 },
  { keyword: "precio lavarropas automático", categoria: "lavarropas", volume: 90 },
  { keyword: "precio secarropas nuevo", categoria: "lavarropas", volume: 90 },
  { keyword: "promociones lavarropas automaticos", categoria: "lavarropas", volume: 90 },
  { keyword: "seca ropa por calor", categoria: "lavarropas", volume: 90 },
  { keyword: "tipos de lavarropas automaticos", categoria: "lavarropas", volume: 90 },
  { keyword: "cual es el mejor lavarropas carga superior", categoria: "lavarropas", volume: 70 },
  { keyword: "cual es el mejor lavarropas de carga superior en argentina", categoria: "lavarropas", volume: 70 },
  { keyword: "inverter lavarropas", categoria: "lavarropas", volume: 70 },
  { keyword: "lavaropa semi automatico", categoria: "lavarropas", volume: 70 },
  { keyword: "lavarropa automatico y semiautomatico", categoria: "lavarropas", volume: 70 },
  { keyword: "lavarropas 13 5 kg", categoria: "lavarropas", volume: 70 },
  { keyword: "lavarropas automatico 15kg", categoria: "lavarropas", volume: 70 },
  { keyword: "lavarropas automatico ahora 12", categoria: "lavarropas", volume: 70 },
  { keyword: "lavarropas automatico carga vertical", categoria: "lavarropas", volume: 70 },
  { keyword: "lavarropas automático inverter", categoria: "lavarropas", volume: 70 },
  { keyword: "lavarropas automaticos 12 kg", categoria: "lavarropas", volume: 70 },
  { keyword: "lavarropas de", categoria: "lavarropas", volume: 70 },
  { keyword: "lavarropas de 4 kilos", categoria: "lavarropas", volume: 70 },
  { keyword: "lavarropas motor inverter", categoria: "lavarropas", volume: 70 },
  { keyword: "no entra agua al lavarropas", categoria: "lavarropas", volume: 70 },
  { keyword: "precio de lavarropas de 8 kilos", categoria: "lavarropas", volume: 70 },
  { keyword: "que marca de lavarropas es mejor", categoria: "lavarropas", volume: 70 },
];
