// Índice LIVIANO de la guía (id → título), para componentes cliente que no deben cargar todo el
// contenido (p. ej. el drawer de KPI, montado en el layout). Espejo de lib/guia/index.ts:
// si agregás o renombrás un módulo, actualizá esta lista (mismo id y título).
export const MODULO_TITULO: Record<string, string> = {
  "proceso-estrategico": "El Proceso Estratégico",
  "ciclo-construir": "01 · Construir: la base del trimestre",
  "ciclo-aprender": "02 · Aprender: leer real vs meta y entender por qué",
  "ciclo-optimizar": "03 · Optimizar: reasignar con evidencia",
  "ciclo-acelerar": "04 · Acelerar: escalar y recalibrar",
  "salud-de-marca": "Posicionamiento y salud de marca",
  "objetivos-negocio-marketing": "Fijar objetivos de negocio y de marketing",
  "modelo-objetivos-kpis": "El modelo: objetivos → KPIs → pesos → metas",
  "metas-mensuales": "Metas mensuales realistas y estacionalidad",
  "presupuesto-marketing": "Presupuesto de marketing: cuánto y cómo repartir",
  "medicion-atribucion": "Medición y atribución: MTA, MMM e incrementalidad",
  "funnel-360": "El funnel 360 y el rol de cada canal",
  "investigacion-competencia": "Investigación de mercado y competencia",
  "plan-de-medios": "Plan de medios por etapa del funnel",
  "medios-offline": "Medios offline y medios sin API: cómo entran y cómo se leen",
  "alcance-frecuencia": "Alcance, frecuencia efectiva y saturación",
  "benchmarks-medios": "Cómo evaluar cada pieza según formato y objetivo",
  "creatividades": "Creatividades que funcionan",
  "reasignacion-inversion": "Reasignar inversión con evidencia",
  "campanas-estacionales": "Campañas estacionales y eventos comerciales",
  "brief-campana": "El brief de campaña",
  "influencers-ugc": "Influencers y contenido generado por usuarios (UGC)",
  "contenido-organico": "Estrategia de contenido orgánico",
  "lectura-redes": "Leer redes: engagement de valor, sentimiento y competencia",
  "seo-share-of-search": "SEO y Share of Search",
  "web-cro": "Web, CRO y embudo de conversión",
  "crm-email": "CRM, email y ciclo de vida del cliente",
  "trade-marketing": "Trade marketing y punto de venta",
  "plan-de-accion": "De los insights al plan de acción",
  "reporte-mensual": "La revisión mensual: agenda y ritual",
  "meta-ads-estructura": "Meta Ads: estructura y objetivo por etapa",
  "meta-ads-audiencias": "Meta Ads: audiencias, Advantage+, presupuesto y frecuencia",
  "meta-pixel-capi": "Meta: píxel y API de Conversiones",
  "lectura-video": "Métricas de video: ThruPlay, VTR y CPCV",
  "google-search": "Google Ads: campañas de búsqueda",
  "google-pmax": "Google Ads: Performance Max",
  "google-demand-gen-youtube": "Google Ads: Demand Gen y YouTube",
  "tiktok-ads": "TikTok Ads: objetivos, creatividad nativa y Spark Ads",
  "ga4-configuracion": "GA4: propiedad, eventos clave y ecommerce",
  "utm-nomenclatura": "UTM y nomenclatura de campañas",
  "search-console": "Search Console: diagnóstico del SEO",
  "conectar-fuentes": "Fuentes de datos, monitoreo y carga de metas",
  "mapa-estrategico": "Armar el Mapa Estratégico paso a paso",
  "insights-chat": "Usar el Diagnóstico IA y el copiloto para decidir",
  "tableros-planilla": "Inversión, Resultados y Trade: de dónde sale cada dato",
};
